#
# (C) COPYRIGHT 2012 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained
# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA.
#
#

ifeq ($(CFG_HI_EXPORT_FLAG),)
ifneq ($(srctree),)
    KERNEL_DIR := $(srctree)
    SDK_DIR := $(shell cd $(KERNEL_DIR)/../../../.. && /bin/pwd)
else
    SDK_DIR := $(shell cd $(CURDIR)/../../../.. && /bin/pwd)
endif
    include $(SDK_DIR)/base.mak
endif

EXTRA_CFLAGS += -I$(DRV_DIR)/include

export CONFIG_HI_DMA_BUFFER_EXPORTER=$(HI_DRV_BUILDTYPE)
obj-$(CONFIG_HI_DMA_BUFFER_EXPORTER) += hi_dbe.o
