/*
 * Copyright (C) Hisilicon Technologies Co., Ltd. 2019. All rights reserved.
 * Description:
 * Author: Automatic generated by nManager v4.0
 * Create: 2019-06-28
 */

#ifndef __HI_REG_PERI_H__
#define __HI_REG_PERI_H__

/* Define the union U_PERI_MEM_CTRL */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    reserved_0            : 31  ; /* [30..0]  */
        unsigned int    peri_ram_ck_gt_en     : 1   ; /* [31]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_MEM_CTRL;

/* Define the union U_PERI_MEM_CTRL_0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_rfs_ema          : 3   ; /* [2..0]  */
        unsigned int    peri_rfs_emaw         : 2   ; /* [4..3]  */
        unsigned int    peri_rfs_rme          : 1   ; /* [5]  */
        unsigned int    peri_rfs_rm           : 4   ; /* [9..6]  */
        unsigned int    reserved_0            : 6   ; /* [15..10]  */
        unsigned int    peri_ras_ema          : 3   ; /* [18..16]  */
        unsigned int    peri_ras_emaw         : 2   ; /* [20..19]  */
        unsigned int    peri_ras_rme          : 1   ; /* [21]  */
        unsigned int    peri_ras_rm           : 4   ; /* [25..22]  */
        unsigned int    reserved_1            : 6   ; /* [31..26]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_MEM_CTRL_0;

/* Define the union U_PERI_MEM_CTRL_1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_rft_emaa         : 3   ; /* [2..0]  */
        unsigned int    peri_rft_emab         : 3   ; /* [5..3]  */
        unsigned int    peri_rft_emasa        : 1   ; /* [6]  */
        unsigned int    peri_rft_colldisn     : 1   ; /* [7]  */
        unsigned int    peri_rft_rmea         : 1   ; /* [8]  */
        unsigned int    peri_rft_rma          : 4   ; /* [12..9]  */
        unsigned int    peri_rft_rmeb         : 1   ; /* [13]  */
        unsigned int    peri_rft_rmb          : 4   ; /* [17..14]  */
        unsigned int    reserved_0            : 6   ; /* [23..18]  */
        unsigned int    peri_ros_ema          : 3   ; /* [26..24]  */
        unsigned int    peri_ros_rme          : 1   ; /* [27]  */
        unsigned int    peri_ros_rm           : 4   ; /* [31..28]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_MEM_CTRL_1;

/* Define the union U_PERI_JTAG_CTRL */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    reserved_0            : 29  ; /* [28..0]  */
        unsigned int    peri_jtag_sel         : 3   ; /* [31..29]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_JTAG_CTRL;

/* Define the union U_PERI_CTRL_1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_sata0_pwren      : 1   ; /* [0]  */
        unsigned int    reserved_0            : 7   ; /* [7..1]  */
        unsigned int    peri_rgmii0_rst_od_sel : 1   ; /* [8]  */
        unsigned int    peri_rgmii1_rst_od_sel : 1   ; /* [9]  */
        unsigned int    reserved_1            : 6   ; /* [15..10]  */
        unsigned int    peri_combphy2_0_phy_mode : 2   ; /* [17..16]  */
        unsigned int    peri_combphy2_1_phy_mode : 2   ; /* [19..18]  */
        unsigned int    peri_combphy2_2_phy_mode : 2   ; /* [21..20]  */
        unsigned int    peri_combphy2_3_phy_mode : 2   ; /* [23..22]  */
        unsigned int    peri_pcie_sel         : 1   ; /* [24]  */
        unsigned int    reserved_2            : 3   ; /* [27..25]  */
        unsigned int    peri_combphy2_mode_sel : 4   ; /* [31..28]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_CTRL_1;

/* Define the union U_PERI_CTRL_2 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_ssp0_cs_sel      : 1   ; /* [0]  */
        unsigned int    reserved_0            : 7   ; /* [7..1]  */
        unsigned int    peri_sdio0_ioshare_sel : 1   ; /* [8]  */
        unsigned int    reserved_1            : 23  ; /* [31..9]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_CTRL_2;

/* Define the union U_PERI_DFT_CTRL */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_func_mbist_clk_sel : 1   ; /* [0]  */
        unsigned int    reserved_0            : 7   ; /* [7..1]  */
        unsigned int    peri_sms_func_mbist_mode : 1   ; /* [8]  */
        unsigned int    reserved_1            : 23  ; /* [31..9]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_DFT_CTRL;

/* Define the union U_PERI_CPU_DFT_CTRL0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_cpu_writeen      : 1   ; /* [0]  */
        unsigned int    reserved_0            : 7   ; /* [7..1]  */
        unsigned int    peri_cpu_enable       : 1   ; /* [8]  */
        unsigned int    reserved_1            : 7   ; /* [15..9]  */
        unsigned int    peri_cpu_resetn       : 1   ; /* [16]  */
        unsigned int    reserved_2            : 15  ; /* [31..17]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_CPU_DFT_CTRL0;

/* Define the union U_PERI_CPU_DFT_CTRL1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_cluster0_dft_mbist1_req : 1   ; /* [0]  */
        unsigned int    peri_cluster0_dft_mbist2_req : 1   ; /* [1]  */
        unsigned int    peri_cluster0_dft_mbist3_req : 1   ; /* [2]  */
        unsigned int    reserved_0            : 5   ; /* [7..3]  */
        unsigned int    peri_cluster0_dft_cpu_mbist_clk_gate : 1   ; /* [8]  */
        unsigned int    reserved_1            : 7   ; /* [15..9]  */
        unsigned int    peri_cluster0_dft_cpu_dft_mbist_cpu_reset_n : 1   ; /* [16]  */
        unsigned int    reserved_2            : 7   ; /* [23..17]  */
        unsigned int    peri_cluster0_cpu_dft_mbist_ctrl_rst_n : 1   ; /* [24]  */
        unsigned int    reserved_3            : 7   ; /* [31..25]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_CPU_DFT_CTRL1;

/* Define the union U_PERI_CPU_DFT_CTRL2 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_cluster1_dft_mbist1_req : 1   ; /* [0]  */
        unsigned int    peri_cluster1_dft_mbist2_req : 1   ; /* [1]  */
        unsigned int    peri_cluster1_dft_mbist3_req : 1   ; /* [2]  */
        unsigned int    reserved_0            : 5   ; /* [7..3]  */
        unsigned int    peri_cluster1_dft_cpu_mbist_clk_gate : 1   ; /* [8]  */
        unsigned int    reserved_1            : 7   ; /* [15..9]  */
        unsigned int    peri_cluster1_dft_cpu_dft_mbist_cpu_reset_n : 1   ; /* [16]  */
        unsigned int    reserved_2            : 7   ; /* [23..17]  */
        unsigned int    peri_cluster1_cpu_dft_mbist_ctrl_rst_n : 1   ; /* [24]  */
        unsigned int    reserved_3            : 7   ; /* [31..25]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_CPU_DFT_CTRL2;

/* Define the union U_PERI_GPU_DFT_CTRL */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_gpu_mbistreq     : 1   ; /* [0]  */
        unsigned int    reserved_0            : 7   ; /* [7..1]  */
        unsigned int    peri_gpu_dftcgen      : 1   ; /* [8]  */
        unsigned int    reserved_1            : 7   ; /* [15..9]  */
        unsigned int    peri_gpu_nmbistreset  : 1   ; /* [16]  */
        unsigned int    reserved_2            : 15  ; /* [31..17]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_GPU_DFT_CTRL;

/* Define the union U_PERI_NPU_DFT_CTRL */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_npu_mbistreq     : 1   ; /* [0]  */
        unsigned int    reserved_0            : 7   ; /* [7..1]  */
        unsigned int    peri_npu_dft_cgen     : 1   ; /* [8]  */
        unsigned int    reserved_1            : 7   ; /* [15..9]  */
        unsigned int    peri_npu_mbist_resetn : 1   ; /* [16]  */
        unsigned int    reserved_2            : 15  ; /* [31..17]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_NPU_DFT_CTRL;

/* Define the union U_PERI_START_MODE */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    reserved_0            : 9   ; /* [8..0]  */
        unsigned int    peri_boot_sel         : 3   ; /* [11..9]  */
        unsigned int    reserved_1            : 8   ; /* [19..12]  */
        unsigned int    peri_romboot_sel      : 1   ; /* [20]  */
        unsigned int    reserved_2            : 1   ; /* [21]  */
        unsigned int    peri_otp_clk_sel_in   : 1   ; /* [22]  */
        unsigned int    peri_jtag_sel_in      : 1   ; /* [23]  */
        unsigned int    peri_self_boot        : 1   ; /* [24]  */
        unsigned int    reserved_3            : 3   ; /* [27..25]  */
        unsigned int    peri_pin_secure_boot_en : 4   ; /* [31..28]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_START_MODE;

/* Define the union U_PERI_CPU_STATE */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    reserved_0            : 16  ; /* [15..0]  */
        unsigned int    peri_cluster0_dbgack  : 1   ; /* [16]  */
        unsigned int    peri_cluster1_dbgack  : 1   ; /* [17]  */
        unsigned int    reserved_1            : 14  ; /* [31..18]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_CPU_STATE;

/* Define the union U_PERI_QOS_PRO_CFG0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_cpu_arqos        : 3   ; /* [2..0]  */
        unsigned int    reserved_0            : 1   ; /* [3]  */
        unsigned int    peri_cpu_awqos        : 3   ; /* [6..4]  */
        unsigned int    reserved_1            : 1   ; /* [7]  */
        unsigned int    peri_gpu_arqos        : 3   ; /* [10..8]  */
        unsigned int    reserved_2            : 1   ; /* [11]  */
        unsigned int    peri_gpu_awqos        : 3   ; /* [14..12]  */
        unsigned int    reserved_3            : 1   ; /* [15]  */
        unsigned int    peri_npu_arqos        : 3   ; /* [18..16]  */
        unsigned int    reserved_4            : 1   ; /* [19]  */
        unsigned int    peri_npu_awqos        : 3   ; /* [22..20]  */
        unsigned int    reserved_5            : 9   ; /* [31..23]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_QOS_PRO_CFG0;

/* Define the union U_PERI_QOS_SEC_CFG0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_dmx_arqos        : 3   ; /* [2..0]  */
        unsigned int    reserved_0            : 1   ; /* [3]  */
        unsigned int    peri_dmx_awqos        : 3   ; /* [6..4]  */
        unsigned int    reserved_1            : 1   ; /* [7]  */
        unsigned int    peri_tsc_arqos        : 3   ; /* [10..8]  */
        unsigned int    reserved_2            : 1   ; /* [11]  */
        unsigned int    peri_tsc_awqos        : 3   ; /* [14..12]  */
        unsigned int    reserved_3            : 17  ; /* [31..15]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_QOS_SEC_CFG0;

/* Define the union U_PERI_QOS_SEC_CFG1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_spacc_arqos      : 3   ; /* [2..0]  */
        unsigned int    reserved_0            : 1   ; /* [3]  */
        unsigned int    peri_spacc_awqos      : 3   ; /* [6..4]  */
        unsigned int    reserved_1            : 1   ; /* [7]  */
        unsigned int    peri_scipher_qos      : 3   ; /* [10..8]  */
        unsigned int    reserved_2            : 5   ; /* [15..11]  */
        unsigned int    peri_sha3_arqos       : 3   ; /* [18..16]  */
        unsigned int    reserved_3            : 13  ; /* [31..19]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_QOS_SEC_CFG1;

/* Define the union U_PERI_QOS_DDR_CFG0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_pastc_arqos      : 3   ; /* [2..0]  */
        unsigned int    reserved_0            : 1   ; /* [3]  */
        unsigned int    peri_pastc_awqos      : 3   ; /* [6..4]  */
        unsigned int    reserved_1            : 1   ; /* [7]  */
        unsigned int    peri_ddrt_arqos       : 3   ; /* [10..8]  */
        unsigned int    reserved_2            : 1   ; /* [11]  */
        unsigned int    peri_ddrt_awqos       : 3   ; /* [14..12]  */
        unsigned int    reserved_3            : 17  ; /* [31..15]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_QOS_DDR_CFG0;

/* Define the union U_PERI_QOS_OFFLINE_CFG0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_jpgd_arqos       : 3   ; /* [2..0]  */
        unsigned int    reserved_0            : 1   ; /* [3]  */
        unsigned int    peri_jpgd_awqos       : 3   ; /* [6..4]  */
        unsigned int    reserved_1            : 1   ; /* [7]  */
        unsigned int    peri_jpge_arqos       : 3   ; /* [10..8]  */
        unsigned int    reserved_2            : 1   ; /* [11]  */
        unsigned int    peri_jpge_awqos       : 3   ; /* [14..12]  */
        unsigned int    reserved_3            : 1   ; /* [15]  */
        unsigned int    peri_pgd_arqos        : 3   ; /* [18..16]  */
        unsigned int    reserved_4            : 1   ; /* [19]  */
        unsigned int    peri_pgd_awqos        : 3   ; /* [22..20]  */
        unsigned int    reserved_5            : 9   ; /* [31..23]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_QOS_OFFLINE_CFG0;

/* Define the union U_PERI_QOS_OFFLINE_CFG1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_vpss_arqos       : 3   ; /* [2..0]  */
        unsigned int    reserved_0            : 1   ; /* [3]  */
        unsigned int    peri_vpss_awqos       : 3   ; /* [6..4]  */
        unsigned int    reserved_1            : 1   ; /* [7]  */
        unsigned int    peri_tde_arqos        : 3   ; /* [10..8]  */
        unsigned int    reserved_2            : 1   ; /* [11]  */
        unsigned int    peri_tde_awqos        : 3   ; /* [14..12]  */
        unsigned int    reserved_3            : 1   ; /* [15]  */
        unsigned int    peri_vedu_arqos       : 3   ; /* [18..16]  */
        unsigned int    reserved_4            : 1   ; /* [19]  */
        unsigned int    peri_vedu_awqos       : 3   ; /* [22..20]  */
        unsigned int    reserved_5            : 9   ; /* [31..23]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_QOS_OFFLINE_CFG1;

/* Define the union U_PERI_QOS_ONLINE_CFG0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_vdh_arqos        : 3   ; /* [2..0]  */
        unsigned int    reserved_0            : 1   ; /* [3]  */
        unsigned int    peri_vdh_awqos        : 3   ; /* [6..4]  */
        unsigned int    reserved_1            : 1   ; /* [7]  */
        unsigned int    peri_vdhbsp_arqos     : 3   ; /* [10..8]  */
        unsigned int    reserved_2            : 1   ; /* [11]  */
        unsigned int    peri_vdhbsp_awqos     : 3   ; /* [14..12]  */
        unsigned int    reserved_3            : 5   ; /* [19..15]  */
        unsigned int    peri_vicap_awqos      : 3   ; /* [22..20]  */
        unsigned int    reserved_4            : 1   ; /* [23]  */
        unsigned int    peri_vdp_arqos        : 3   ; /* [26..24]  */
        unsigned int    reserved_5            : 1   ; /* [27]  */
        unsigned int    peri_vdp_awqos        : 3   ; /* [30..28]  */
        unsigned int    reserved_6            : 1   ; /* [31]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_QOS_ONLINE_CFG0;

/* Define the union U_PERI_QOS_ONLINE_CFG1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_vmcu_arqos       : 3   ; /* [2..0]  */
        unsigned int    reserved_0            : 1   ; /* [3]  */
        unsigned int    peri_vmcu_awqos       : 3   ; /* [6..4]  */
        unsigned int    reserved_1            : 9   ; /* [15..7]  */
        unsigned int    peri_vdma_qos         : 3   ; /* [18..16]  */
        unsigned int    reserved_2            : 13  ; /* [31..19]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_QOS_ONLINE_CFG1;

/* Define the union U_PERI_QOS_AUDIO_CFG0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_aiao_arqos       : 3   ; /* [2..0]  */
        unsigned int    reserved_0            : 1   ; /* [3]  */
        unsigned int    peri_aiao_awqos       : 3   ; /* [6..4]  */
        unsigned int    reserved_1            : 1   ; /* [7]  */
        unsigned int    peri_adsp_arqos       : 3   ; /* [10..8]  */
        unsigned int    reserved_2            : 1   ; /* [11]  */
        unsigned int    peri_adsp_awqos       : 3   ; /* [14..12]  */
        unsigned int    reserved_3            : 1   ; /* [15]  */
        unsigned int    peri_aidsp_arqos      : 3   ; /* [18..16]  */
        unsigned int    reserved_4            : 1   ; /* [19]  */
        unsigned int    peri_aidsp_awqos      : 3   ; /* [22..20]  */
        unsigned int    reserved_5            : 9   ; /* [31..23]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_QOS_AUDIO_CFG0;

/* Define the union U_PERI_QOS_PERI_CFG0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_usb2_1_arqos     : 3   ; /* [2..0]  */
        unsigned int    reserved_0            : 1   ; /* [3]  */
        unsigned int    peri_usb2_1_awqos     : 3   ; /* [6..4]  */
        unsigned int    reserved_1            : 1   ; /* [7]  */
        unsigned int    peri_usb2_0_arqos     : 3   ; /* [10..8]  */
        unsigned int    reserved_2            : 1   ; /* [11]  */
        unsigned int    peri_usb2_0_awqos     : 3   ; /* [14..12]  */
        unsigned int    reserved_3            : 1   ; /* [15]  */
        unsigned int    peri_usb31_arqos      : 3   ; /* [18..16]  */
        unsigned int    reserved_4            : 1   ; /* [19]  */
        unsigned int    peri_usb31_awqos      : 3   ; /* [22..20]  */
        unsigned int    reserved_5            : 9   ; /* [31..23]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_QOS_PERI_CFG0;

/* Define the union U_PERI_QOS_PERI_CFG1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_sdio0_arqos      : 3   ; /* [2..0]  */
        unsigned int    reserved_0            : 1   ; /* [3]  */
        unsigned int    peri_sdio0_awqos      : 3   ; /* [6..4]  */
        unsigned int    reserved_1            : 1   ; /* [7]  */
        unsigned int    peri_sdio1_arqos      : 3   ; /* [10..8]  */
        unsigned int    reserved_2            : 1   ; /* [11]  */
        unsigned int    peri_sdio1_awqos      : 3   ; /* [14..12]  */
        unsigned int    reserved_3            : 1   ; /* [15]  */
        unsigned int    peri_fmc_qos          : 3   ; /* [18..16]  */
        unsigned int    reserved_4            : 5   ; /* [23..19]  */
        unsigned int    peri_emmc_arqos       : 3   ; /* [26..24]  */
        unsigned int    reserved_5            : 1   ; /* [27]  */
        unsigned int    peri_emmc_awqos       : 3   ; /* [30..28]  */
        unsigned int    reserved_6            : 1   ; /* [31]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_QOS_PERI_CFG1;

/* Define the union U_PERI_QOS_PERI_CFG2 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_eth_arqos        : 3   ; /* [2..0]  */
        unsigned int    reserved_0            : 1   ; /* [3]  */
        unsigned int    peri_eth_awqos        : 3   ; /* [6..4]  */
        unsigned int    reserved_1            : 1   ; /* [7]  */
        unsigned int    peri_pcie_arqos       : 3   ; /* [10..8]  */
        unsigned int    reserved_2            : 1   ; /* [11]  */
        unsigned int    peri_pcie_awqos       : 3   ; /* [14..12]  */
        unsigned int    reserved_3            : 1   ; /* [15]  */
        unsigned int    peri_sata_arqos       : 3   ; /* [18..16]  */
        unsigned int    reserved_4            : 1   ; /* [19]  */
        unsigned int    peri_sata_awqos       : 3   ; /* [22..20]  */
        unsigned int    reserved_5            : 9   ; /* [31..23]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_QOS_PERI_CFG2;

/* Define the union U_PERI_QOS_PERI_CFG3 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_tsio_arqos       : 3   ; /* [2..0]  */
        unsigned int    reserved_0            : 1   ; /* [3]  */
        unsigned int    peri_tsio_awqos       : 3   ; /* [6..4]  */
        unsigned int    reserved_1            : 25  ; /* [31..7]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_QOS_PERI_CFG3;

/* Define the union U_PERI_MMU_QOS */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_mmu_pref_qos     : 3   ; /* [2..0]  */
        unsigned int    reserved_0            : 29  ; /* [31..3]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_MMU_QOS;

/* Define the union U_PERI_QOS_MEDIA1_AXI */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_m1_axi_m4qos     : 2   ; /* [1..0]  */
        unsigned int    reserved_0            : 2   ; /* [3..2]  */
        unsigned int    peri_m1_axi_m3qos     : 2   ; /* [5..4]  */
        unsigned int    reserved_1            : 2   ; /* [7..6]  */
        unsigned int    peri_m1_axi_m2qos     : 2   ; /* [9..8]  */
        unsigned int    reserved_2            : 2   ; /* [11..10]  */
        unsigned int    peri_m1_axi_m1qos     : 2   ; /* [13..12]  */
        unsigned int    reserved_3            : 18  ; /* [31..14]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_QOS_MEDIA1_AXI;

/* Define the union U_PERI_QOS_MEDIA3_AXI */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_m3_axi_m3qos     : 2   ; /* [1..0]  */
        unsigned int    reserved_0            : 2   ; /* [3..2]  */
        unsigned int    peri_m3_axi_m2qos     : 2   ; /* [5..4]  */
        unsigned int    reserved_1            : 2   ; /* [7..6]  */
        unsigned int    peri_m3_axi_m1qos     : 2   ; /* [9..8]  */
        unsigned int    reserved_2            : 22  ; /* [31..10]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_QOS_MEDIA3_AXI;

/* Define the union U_PERI_QOS_PERI1_AXI */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_peri1_axi_m6qos  : 3   ; /* [2..0]  */
        unsigned int    reserved_0            : 1   ; /* [3]  */
        unsigned int    peri_peri1_axi_m5qos  : 3   ; /* [6..4]  */
        unsigned int    reserved_1            : 1   ; /* [7]  */
        unsigned int    peri_peri1_axi_m4qos  : 3   ; /* [10..8]  */
        unsigned int    reserved_2            : 1   ; /* [11]  */
        unsigned int    peri_peri1_axi_m3qos  : 3   ; /* [14..12]  */
        unsigned int    reserved_3            : 1   ; /* [15]  */
        unsigned int    peri_peri1_axi_m2qos  : 3   ; /* [18..16]  */
        unsigned int    reserved_4            : 1   ; /* [19]  */
        unsigned int    peri_peri1_axi_m1qos  : 3   ; /* [22..20]  */
        unsigned int    reserved_5            : 9   ; /* [31..23]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_QOS_PERI1_AXI;

/* Define the union U_PERI_QOS_PERI1_SEC_AXI */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_peri1_sec_axi_m6qos : 3   ; /* [2..0]  */
        unsigned int    reserved_0            : 1   ; /* [3]  */
        unsigned int    peri_peri1_sec_axi_m5qos : 3   ; /* [6..4]  */
        unsigned int    reserved_1            : 1   ; /* [7]  */
        unsigned int    peri_peri1_sec_axi_m4qos : 3   ; /* [10..8]  */
        unsigned int    reserved_2            : 1   ; /* [11]  */
        unsigned int    peri_peri1_sec_axi_m3qos : 3   ; /* [14..12]  */
        unsigned int    reserved_3            : 1   ; /* [15]  */
        unsigned int    peri_peri1_sec_axi_m2qos : 3   ; /* [18..16]  */
        unsigned int    reserved_4            : 1   ; /* [19]  */
        unsigned int    peri_peri1_sec_axi_m1qos : 3   ; /* [22..20]  */
        unsigned int    reserved_5            : 9   ; /* [31..23]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_QOS_PERI1_SEC_AXI;

/* Define the union U_PERI_QOS_CPU_DDR_AXI */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_cpuddraxi_m1qos  : 1   ; /* [0]  */
        unsigned int    reserved_0            : 3   ; /* [3..1]  */
        unsigned int    peri_cpuddraxi_m2qos  : 1   ; /* [4]  */
        unsigned int    reserved_1            : 27  ; /* [31..5]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_QOS_CPU_DDR_AXI;

/* Define the union U_PERI_USB2_0_PHY_CTRL0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_usb2_0_phy_atereset : 1   ; /* [0]  */
        unsigned int    peri_usb2_0_phy_siddq : 1   ; /* [1]  */
        unsigned int    peri_usb2_0_phy_vatestenb : 2   ; /* [3..2]  */
        unsigned int    peri_usb2_0_phy_commononn : 1   ; /* [4]  */
        unsigned int    peri_usb2_0_phy_pllitune : 2   ; /* [6..5]  */
        unsigned int    peri_usb2_0_phy_pllptune : 4   ; /* [10..7]  */
        unsigned int    peri_usb2_0_phy_pllbtune : 1   ; /* [11]  */
        unsigned int    reserved_0            : 1   ; /* [12]  */
        unsigned int    peri_usb2_0_phy_retenablen : 1   ; /* [13]  */
        unsigned int    peri_usb2_0_phy_loopbackenb : 1   ; /* [14]  */
        unsigned int    peri_usb2_0_phy_autorsmenb : 1   ; /* [15]  */
        unsigned int    peri_usb2_0_phy_hsxcvrextctl : 1   ; /* [16]  */
        unsigned int    peri_usb2_0_phy_compdistune : 3   ; /* [19..17]  */
        unsigned int    peri_usb2_0_phy_sqrxtune : 3   ; /* [22..20]  */
        unsigned int    peri_usb2_0_phy_vdatreftune : 2   ; /* [24..23]  */
        unsigned int    peri_usb2_0_phy_otgtune : 3   ; /* [27..25]  */
        unsigned int    peri_usb2_0_phy_txhsxvtune : 2   ; /* [29..28]  */
        unsigned int    peri_usb2_0_phy_testburnin : 1   ; /* [30]  */
        unsigned int    peri_usb2_0_phy_sleepm : 1   ; /* [31]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_USB2_0_PHY_CTRL0;

/* Define the union U_PERI_USB2_0_PHY_CTRL1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_usb2_0_phy_txfslstune : 4   ; /* [3..0]  */
        unsigned int    peri_usb2_0_phy_txvreftune : 4   ; /* [7..4]  */
        unsigned int    peri_usb2_0_phy_txrisetune : 2   ; /* [9..8]  */
        unsigned int    peri_usb2_0_phy_txrestune : 2   ; /* [11..10]  */
        unsigned int    peri_usb2_0_phy_txpreempamptune : 2   ; /* [13..12]  */
        unsigned int    peri_usb2_0_phy_txpreemppulsetune : 1   ; /* [14]  */
        unsigned int    peri_usb2_0_phy_vbusvldext : 1   ; /* [15]  */
        unsigned int    peri_usb2_0_phy_vbusvldextsel : 1   ; /* [16]  */
        unsigned int    peri_usb2_0_phy_txbitstuffenh : 1   ; /* [17]  */
        unsigned int    peri_usb2_0_phy_txbitstuffen : 1   ; /* [18]  */
        unsigned int    peri_usb2_0_phy_wordinterface : 1   ; /* [19]  */
        unsigned int    peri_usb2_0_phy_idpullup : 1   ; /* [20]  */
        unsigned int    reserved_0            : 11  ; /* [31..21]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_USB2_0_PHY_CTRL1;

/* Define the union U_PERI_USB2_0_PHY_CTRL2 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_usb2_0_phy_testclk : 1   ; /* [0]  */
        unsigned int    peri_usb2_0_phy_testdataoutsel : 1   ; /* [1]  */
        unsigned int    peri_usb2_0_phy_testen : 1   ; /* [2]  */
        unsigned int    reserved_0            : 1   ; /* [3]  */
        unsigned int    peri_usb2_0_phy_testaddr : 4   ; /* [7..4]  */
        unsigned int    peri_usb2_0_phy_testdatain : 8   ; /* [15..8]  */
        unsigned int    peri_usb2_0_phy_testdataout : 4   ; /* [19..16]  */
        unsigned int    reserved_1            : 12  ; /* [31..20]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_USB2_0_PHY_CTRL2;

/* Define the union U_PERI_USB2_1_PHY_CTRL0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_usb2_1_phy_atereset : 1   ; /* [0]  */
        unsigned int    peri_usb2_1_phy_siddq : 1   ; /* [1]  */
        unsigned int    peri_usb2_1_phy_vatestenb : 2   ; /* [3..2]  */
        unsigned int    peri_usb2_1_phy_commononn : 1   ; /* [4]  */
        unsigned int    peri_usb2_1_phy_pllitune : 2   ; /* [6..5]  */
        unsigned int    peri_usb2_1_phy_pllptune : 4   ; /* [10..7]  */
        unsigned int    peri_usb2_1_phy_pllbtune : 1   ; /* [11]  */
        unsigned int    reserved_0            : 1   ; /* [12]  */
        unsigned int    peri_usb2_1_phy_retenablen : 1   ; /* [13]  */
        unsigned int    peri_usb2_1_phy_loopbackenb : 1   ; /* [14]  */
        unsigned int    peri_usb2_1_phy_autorsmenb : 1   ; /* [15]  */
        unsigned int    peri_usb2_1_phy_hsxcvrextctl : 1   ; /* [16]  */
        unsigned int    peri_usb2_1_phy_compdistune : 3   ; /* [19..17]  */
        unsigned int    peri_usb2_1_phy_sqrxtune : 3   ; /* [22..20]  */
        unsigned int    peri_usb2_1_phy_vdatreftune : 2   ; /* [24..23]  */
        unsigned int    peri_usb2_1_phy_otgtune : 3   ; /* [27..25]  */
        unsigned int    peri_usb2_1_phy_txhsxvtune : 2   ; /* [29..28]  */
        unsigned int    peri_usb2_1_phy_testburnin : 1   ; /* [30]  */
        unsigned int    peri_usb2_1_phy_sleepm : 1   ; /* [31]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_USB2_1_PHY_CTRL0;

/* Define the union U_PERI_USB2_1_PHY_CTRL1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_usb2_1_phy_txfslstune : 4   ; /* [3..0]  */
        unsigned int    peri_usb2_1_phy_txvreftune : 4   ; /* [7..4]  */
        unsigned int    peri_usb2_1_phy_txrisetune : 2   ; /* [9..8]  */
        unsigned int    peri_usb2_1_phy_txrestune : 2   ; /* [11..10]  */
        unsigned int    peri_usb2_1_phy_txpreempamptune : 2   ; /* [13..12]  */
        unsigned int    peri_usb2_1_phy_txpreemppulsetune : 1   ; /* [14]  */
        unsigned int    peri_usb2_1_phy_vbusvldext : 1   ; /* [15]  */
        unsigned int    peri_usb2_1_phy_vbusvldextsel : 1   ; /* [16]  */
        unsigned int    peri_usb2_1_phy_txbitstuffenh : 1   ; /* [17]  */
        unsigned int    peri_usb2_1_phy_txbitstuffen : 1   ; /* [18]  */
        unsigned int    peri_usb2_1_phy_wordinterface : 1   ; /* [19]  */
        unsigned int    peri_usb2_1_phy_idpullup : 1   ; /* [20]  */
        unsigned int    reserved_0            : 11  ; /* [31..21]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_USB2_1_PHY_CTRL1;

/* Define the union U_PERI_USB2_1_PHY_CTRL2 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_usb2_1_phy_testclk : 1   ; /* [0]  */
        unsigned int    peri_usb2_1_phy_testdataoutsel : 1   ; /* [1]  */
        unsigned int    peri_usb2_1_phy_testen : 1   ; /* [2]  */
        unsigned int    reserved_0            : 1   ; /* [3]  */
        unsigned int    peri_usb2_1_phy_testaddr : 4   ; /* [7..4]  */
        unsigned int    peri_usb2_1_phy_testdatain : 8   ; /* [15..8]  */
        unsigned int    peri_usb2_1_phy_testdataout : 4   ; /* [19..16]  */
        unsigned int    reserved_1            : 12  ; /* [31..20]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_USB2_1_PHY_CTRL2;

/* Define the union U_PERI_USB3_1_PHY_CTRL0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_usb31_1_phy_atereset : 1   ; /* [0]  */
        unsigned int    peri_usb31_1_phy_siddq : 1   ; /* [1]  */
        unsigned int    peri_usb31_1_phy_vatestenb : 2   ; /* [3..2]  */
        unsigned int    peri_usb31_1_phy_commononn : 1   ; /* [4]  */
        unsigned int    peri_usb31_1_phy_pllitune : 2   ; /* [6..5]  */
        unsigned int    peri_usb31_1_phy_pllptune : 4   ; /* [10..7]  */
        unsigned int    peri_usb31_1_phy_pllbtune : 1   ; /* [11]  */
        unsigned int    reserved_0            : 1   ; /* [12]  */
        unsigned int    peri_usb31_1_phy_retenablen : 1   ; /* [13]  */
        unsigned int    peri_usb31_1_phy_loopbackenb : 1   ; /* [14]  */
        unsigned int    peri_usb31_1_phy_autorsmenb : 1   ; /* [15]  */
        unsigned int    peri_usb31_1_phy_hsxcvrextctl : 1   ; /* [16]  */
        unsigned int    peri_usb31_1_phy_compdistune : 3   ; /* [19..17]  */
        unsigned int    peri_usb31_1_phy_sqrxtune : 3   ; /* [22..20]  */
        unsigned int    peri_usb31_1_phy_vdatreftune : 2   ; /* [24..23]  */
        unsigned int    peri_usb31_1_phy_otgtune : 3   ; /* [27..25]  */
        unsigned int    peri_usb31_1_phy_txhsxvtune : 2   ; /* [29..28]  */
        unsigned int    peri_usb31_1_phy_testburnin : 1   ; /* [30]  */
        unsigned int    peri_usb31_1_phy_sleepm : 1   ; /* [31]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_USB3_1_PHY_CTRL0;

/* Define the union U_PERI_USB3_1_PHY_CTRL1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_usb31_1_phy_txfslstune : 4   ; /* [3..0]  */
        unsigned int    peri_usb31_1_phy_txvreftune : 4   ; /* [7..4]  */
        unsigned int    peri_usb31_1_phy_txrisetune : 2   ; /* [9..8]  */
        unsigned int    peri_usb31_1_phy_txrestune : 2   ; /* [11..10]  */
        unsigned int    peri_usb31_1_phy_txpreempamptune : 2   ; /* [13..12]  */
        unsigned int    peri_usb31_1_phy_txpreemppulsetune : 1   ; /* [14]  */
        unsigned int    peri_usb31_1_phy_vbusvldext : 1   ; /* [15]  */
        unsigned int    peri_usb31_1_phy_vbusvldextsel : 1   ; /* [16]  */
        unsigned int    peri_usb31_1_phy_txbitstuffenh : 1   ; /* [17]  */
        unsigned int    peri_usb31_1_phy_txbitstuffen : 1   ; /* [18]  */
        unsigned int    peri_usb31_1_phy_wordinterface : 1   ; /* [19]  */
        unsigned int    peri_usb31_1_phy_idpullup : 1   ; /* [20]  */
        unsigned int    reserved_0            : 11  ; /* [31..21]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_USB3_1_PHY_CTRL1;

/* Define the union U_PERI_USB3_1_PHY_CTRL2 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_usb31_1_phy_testclk : 1   ; /* [0]  */
        unsigned int    peri_usb31_1_phy_testdataoutsel : 1   ; /* [1]  */
        unsigned int    peri_usb31_1_phy_testen : 1   ; /* [2]  */
        unsigned int    reserved_0            : 1   ; /* [3]  */
        unsigned int    peri_usb31_1_phy_testaddr : 4   ; /* [7..4]  */
        unsigned int    peri_usb31_1_phy_testdatain : 8   ; /* [15..8]  */
        unsigned int    peri_usb31_1_phy_testdataout : 4   ; /* [19..16]  */
        unsigned int    reserved_1            : 12  ; /* [31..20]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_USB3_1_PHY_CTRL2;

/* Define the union U_PERI_COMBPHY1_STATE */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_combphy1_align_detect : 1   ; /* [0]  */
        unsigned int    peri_combphy1_rx_standby_status : 1   ; /* [1]  */
        unsigned int    peri_combphy1_rx_data_valid : 1   ; /* [2]  */
        unsigned int    reserved_0            : 1   ; /* [3]  */
        unsigned int    peri_combphy1_data_bus_width : 2   ; /* [5..4]  */
        unsigned int    reserved_1            : 26  ; /* [31..6]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_COMBPHY1_STATE;

/* Define the union U_PERI_COMBPHY2_CFG0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    reserved_0            : 2   ; /* [1..0]  */
        unsigned int    peri_combphy2_0_tx_pattern : 2   ; /* [3..2]  */
        unsigned int    reserved_1            : 2   ; /* [5..4]  */
        unsigned int    peri_combphy2_0_clk_req : 1   ; /* [6]  */
        unsigned int    reserved_2            : 4   ; /* [10..7]  */
        unsigned int    peri_combphy2_0_rx_standby : 1   ; /* [11]  */
        unsigned int    reserved_3            : 3   ; /* [14..12]  */
        unsigned int    peri_combphy2_0_width : 1   ; /* [15]  */
        unsigned int    peri_combphy2_0_serdes_arch : 1   ; /* [16]  */
        unsigned int    reserved_4            : 3   ; /* [19..17]  */
        unsigned int    peri_combphy2_0_sris_enable : 1   ; /* [20]  */
        unsigned int    reserved_5            : 7   ; /* [27..21]  */
        unsigned int    peri_combphy2_0_buf_mode : 1   ; /* [28]  */
        unsigned int    reserved_6            : 2   ; /* [30..29]  */
        unsigned int    peri_combphy2_0_bypass_codec : 1   ; /* [31]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_COMBPHY2_CFG0;

/* Define the union U_PERI_COMBPHY2_STATE0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_combphy2_0_align_detect : 1   ; /* [0]  */
        unsigned int    peri_combphy2_0_rx_standby_status : 1   ; /* [1]  */
        unsigned int    peri_combphy2_0_rx_data_valid : 1   ; /* [2]  */
        unsigned int    peri_combphy2_0_ref_clk_needed : 1   ; /* [3]  */
        unsigned int    peri_combphy2_0_data_bus_width : 2   ; /* [5..4]  */
        unsigned int    reserved_0            : 26  ; /* [31..6]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_COMBPHY2_STATE0;

/* Define the union U_PERI_COMBPHY2_CFG1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    reserved_0            : 2   ; /* [1..0]  */
        unsigned int    peri_combphy2_1_tx_pattern : 2   ; /* [3..2]  */
        unsigned int    reserved_1            : 2   ; /* [5..4]  */
        unsigned int    peri_combphy2_1_clk_req : 1   ; /* [6]  */
        unsigned int    reserved_2            : 4   ; /* [10..7]  */
        unsigned int    peri_combphy2_1_rx_standby : 1   ; /* [11]  */
        unsigned int    reserved_3            : 3   ; /* [14..12]  */
        unsigned int    peri_combphy2_1_width : 1   ; /* [15]  */
        unsigned int    peri_combphy2_1_serdes_arch : 1   ; /* [16]  */
        unsigned int    reserved_4            : 3   ; /* [19..17]  */
        unsigned int    peri_combphy2_1_sris_enable : 1   ; /* [20]  */
        unsigned int    reserved_5            : 7   ; /* [27..21]  */
        unsigned int    peri_combphy2_1_buf_mode : 1   ; /* [28]  */
        unsigned int    reserved_6            : 2   ; /* [30..29]  */
        unsigned int    peri_combphy2_1_bypass_codec : 1   ; /* [31]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_COMBPHY2_CFG1;

/* Define the union U_PERI_COMBPHY2_STATE1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_combphy2_1_align_detect : 1   ; /* [0]  */
        unsigned int    peri_combphy2_1_rx_standby_status : 1   ; /* [1]  */
        unsigned int    peri_combphy2_1_rx_data_valid : 1   ; /* [2]  */
        unsigned int    peri_combphy2_1_ref_clk_needed : 1   ; /* [3]  */
        unsigned int    peri_combphy2_1_data_bus_width : 2   ; /* [5..4]  */
        unsigned int    reserved_0            : 26  ; /* [31..6]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_COMBPHY2_STATE1;

/* Define the union U_PERI_COMBPHY2_CFG2 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    reserved_0            : 2   ; /* [1..0]  */
        unsigned int    peri_combphy2_2_tx_pattern : 2   ; /* [3..2]  */
        unsigned int    reserved_1            : 2   ; /* [5..4]  */
        unsigned int    peri_combphy2_2_clk_req : 1   ; /* [6]  */
        unsigned int    reserved_2            : 4   ; /* [10..7]  */
        unsigned int    peri_combphy2_2_rx_standby : 1   ; /* [11]  */
        unsigned int    reserved_3            : 3   ; /* [14..12]  */
        unsigned int    peri_combphy2_2_width : 1   ; /* [15]  */
        unsigned int    peri_combphy2_2_serdes_arch : 1   ; /* [16]  */
        unsigned int    reserved_4            : 3   ; /* [19..17]  */
        unsigned int    peri_combphy2_2_sris_enable : 1   ; /* [20]  */
        unsigned int    reserved_5            : 7   ; /* [27..21]  */
        unsigned int    peri_combphy2_2_buf_mode : 1   ; /* [28]  */
        unsigned int    reserved_6            : 2   ; /* [30..29]  */
        unsigned int    peri_combphy2_2_bypass_codec : 1   ; /* [31]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_COMBPHY2_CFG2;

/* Define the union U_PERI_COMBPHY2_STATE2 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_combphy2_2_align_detect : 1   ; /* [0]  */
        unsigned int    peri_combphy2_2_rx_standby_status : 1   ; /* [1]  */
        unsigned int    peri_combphy2_2_rx_data_valid : 1   ; /* [2]  */
        unsigned int    peri_combphy2_2_ref_clk_needed : 1   ; /* [3]  */
        unsigned int    peri_combphy2_2_data_bus_width : 2   ; /* [5..4]  */
        unsigned int    reserved_0            : 26  ; /* [31..6]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_COMBPHY2_STATE2;

/* Define the union U_PERI_PCIE0_IO_CFG */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_pcie0_io_oe      : 1   ; /* [0]  */
        unsigned int    peri_pcie0_io_ie      : 1   ; /* [1]  */
        unsigned int    reserved_0            : 2   ; /* [3..2]  */
        unsigned int    peri_pcie0_io_ds      : 3   ; /* [6..4]  */
        unsigned int    reserved_1            : 1   ; /* [7]  */
        unsigned int    peri_pcie0_io_odt     : 2   ; /* [9..8]  */
        unsigned int    peri_pcie0_io_odt_en  : 1   ; /* [10]  */
        unsigned int    reserved_2            : 1   ; /* [11]  */
        unsigned int    peri_pcie0_io_pe      : 1   ; /* [12]  */
        unsigned int    peri_pcie0_io_psn     : 1   ; /* [13]  */
        unsigned int    peri_pcie0_io_psp     : 1   ; /* [14]  */
        unsigned int    reserved_3            : 1   ; /* [15]  */
        unsigned int    peri_pcie0_io_sr      : 1   ; /* [16]  */
        unsigned int    reserved_4            : 15  ; /* [31..17]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_PCIE0_IO_CFG;

/* Define the union U_PERI_COMBPHY2_CFG3 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    reserved_0            : 2   ; /* [1..0]  */
        unsigned int    peri_combphy2_3_tx_pattern : 2   ; /* [3..2]  */
        unsigned int    reserved_1            : 2   ; /* [5..4]  */
        unsigned int    peri_combphy2_3_clk_req : 1   ; /* [6]  */
        unsigned int    reserved_2            : 4   ; /* [10..7]  */
        unsigned int    peri_combphy2_3_rx_standby : 1   ; /* [11]  */
        unsigned int    reserved_3            : 3   ; /* [14..12]  */
        unsigned int    peri_combphy2_3_width : 1   ; /* [15]  */
        unsigned int    peri_combphy2_3_serdes_arch : 1   ; /* [16]  */
        unsigned int    reserved_4            : 3   ; /* [19..17]  */
        unsigned int    peri_combphy2_3_sris_enable : 1   ; /* [20]  */
        unsigned int    reserved_5            : 7   ; /* [27..21]  */
        unsigned int    peri_combphy2_3_buf_mode : 1   ; /* [28]  */
        unsigned int    reserved_6            : 2   ; /* [30..29]  */
        unsigned int    peri_combphy2_3_bypass_codec : 1   ; /* [31]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_COMBPHY2_CFG3;

/* Define the union U_PERI_COMBPHY2_STATE3 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_combphy2_3_align_detect : 1   ; /* [0]  */
        unsigned int    peri_combphy2_3_rx_standby_status : 1   ; /* [1]  */
        unsigned int    peri_combphy2_3_rx_data_valid : 1   ; /* [2]  */
        unsigned int    peri_combphy2_3_ref_clk_needed : 1   ; /* [3]  */
        unsigned int    peri_combphy2_3_data_bus_width : 2   ; /* [5..4]  */
        unsigned int    reserved_0            : 26  ; /* [31..6]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_COMBPHY2_STATE3;

/* Define the union U_PERI_PCIE1_IO_CFG */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_pcie1_io_oe      : 1   ; /* [0]  */
        unsigned int    peri_pcie1_io_ie      : 1   ; /* [1]  */
        unsigned int    reserved_0            : 2   ; /* [3..2]  */
        unsigned int    peri_pcie1_io_ds      : 3   ; /* [6..4]  */
        unsigned int    reserved_1            : 1   ; /* [7]  */
        unsigned int    peri_pcie1_io_odt     : 2   ; /* [9..8]  */
        unsigned int    peri_pcie1_io_odt_en  : 1   ; /* [10]  */
        unsigned int    reserved_2            : 1   ; /* [11]  */
        unsigned int    peri_pcie1_io_pe      : 1   ; /* [12]  */
        unsigned int    peri_pcie1_io_psn     : 1   ; /* [13]  */
        unsigned int    peri_pcie1_io_psp     : 1   ; /* [14]  */
        unsigned int    reserved_3            : 1   ; /* [15]  */
        unsigned int    peri_pcie1_io_sr      : 1   ; /* [16]  */
        unsigned int    reserved_4            : 15  ; /* [31..17]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_PCIE1_IO_CFG;

/* Define the union U_PERI_USB_RESUME_INT_MASK */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_usb2_0_suspend_int_mask : 1   ; /* [0]  */
        unsigned int    peri_usb2_1_suspend_int_mask : 1   ; /* [1]  */
        unsigned int    reserved_0            : 14  ; /* [15..2]  */
        unsigned int    peri_usb31_0_suspend_int_mask : 1   ; /* [16]  */
        unsigned int    peri_usb31_1_suspend_int_mask : 1   ; /* [17]  */
        unsigned int    reserved_1            : 14  ; /* [31..18]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_USB_RESUME_INT_MASK;

/* Define the union U_PERI_USB_RESUME_INT_RAWSTAT */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_usb2_0_phy_utmi_suspend_n : 1   ; /* [0]  */
        unsigned int    peri_usb2_1_phy_utmi_suspend_n : 1   ; /* [1]  */
        unsigned int    reserved_0            : 14  ; /* [15..2]  */
        unsigned int    peri_usb31_0_phy_utmi_suspend_n : 1   ; /* [16]  */
        unsigned int    peri_usb31_1_phy_utmi_suspend_n : 1   ; /* [17]  */
        unsigned int    reserved_1            : 14  ; /* [31..18]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_USB_RESUME_INT_RAWSTAT;

/* Define the union U_PERI_USB_RESUME_INT_STAT */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_usb2_0_suspend_int_stat : 1   ; /* [0]  */
        unsigned int    peri_usb2_1_suspend_int_stat : 1   ; /* [1]  */
        unsigned int    reserved_0            : 14  ; /* [15..2]  */
        unsigned int    peri_usb31_0_suspend_int_stat : 1   ; /* [16]  */
        unsigned int    peri_usb31_1_suspend_int_stat : 1   ; /* [17]  */
        unsigned int    reserved_1            : 14  ; /* [31..18]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_USB_RESUME_INT_STAT;

/* Define the union U_PERI_PWR_SW_CTRL */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_pwr_sw_en        : 1   ; /* [0]  */
        unsigned int    reserved_0            : 1   ; /* [1]  */
        unsigned int    peri_pwr_sw_sel       : 1   ; /* [2]  */
        unsigned int    reserved_1            : 29  ; /* [31..3]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_PWR_SW_CTRL;

/* Define the union U_PERI_POWER_SEL */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_dvdd3318_spdif_sel : 1   ; /* [0]  */
        unsigned int    peri_dvdd3318_sim_sel : 1   ; /* [1]  */
        unsigned int    peri_dvdd3318_tsi_sel : 1   ; /* [2]  */
        unsigned int    peri_dvdd3318_tso_sel : 1   ; /* [3]  */
        unsigned int    reserved_0            : 28  ; /* [31..4]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_POWER_SEL;

/* Define the union U_PERI_INTF_IO_SEL */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_hdmirx0_i2c_sel  : 2   ; /* [1..0]  */
        unsigned int    reserved_0            : 6   ; /* [7..2]  */
        unsigned int    peri_hdmitx0_i2c_sel  : 2   ; /* [9..8]  */
        unsigned int    reserved_1            : 6   ; /* [15..10]  */
        unsigned int    peri_mipi_ad_sel      : 1   ; /* [16]  */
        unsigned int    reserved_2            : 15  ; /* [31..17]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_INTF_IO_SEL;

/* Define the union U_PERI_GPU_STRIP_CTRL */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_gpu_striping_granule : 3   ; /* [2..0]  */
        unsigned int    reserved_0            : 29  ; /* [31..3]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_GPU_STRIP_CTRL;

/* Define the union U_PERI_NPU_CTRL */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_npubus_intlv_gran : 2   ; /* [1..0]  */
        unsigned int    reserved_0            : 6   ; /* [7..2]  */
        unsigned int    peri_eventi_tscore    : 1   ; /* [8]  */
        unsigned int    reserved_1            : 23  ; /* [31..9]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_NPU_CTRL;

/* Define the union U_PERI_NPU_STATE */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_evento_tscore    : 2   ; /* [1..0]  */
        unsigned int    reserved_0            : 30  ; /* [31..2]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_NPU_STATE;

/* Define the union U_PERI_HDMITX_CTRL */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_hdmitx_ctrl2p0_to_phy2p0 : 1   ; /* [0]  */
        unsigned int    reserved_0            : 31  ; /* [31..1]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_HDMITX_CTRL;

/* Define the union U_PERI_SOFT_INT */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_int_cputomce     : 1   ; /* [0]  */
        unsigned int    reserved_0            : 31  ; /* [31..1]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_SOFT_INT;

/* Define the union U_PERI_SOFT_INT_MASK */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    peri_int_cputomce_mask : 1   ; /* [0]  */
        unsigned int    peri_int_soft_mask    : 7   ; /* [7..1]  */
        unsigned int    reserved_0            : 24  ; /* [31..8]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_PERI_SOFT_INT_MASK;

//==============================================================================
/* Define the global struct */
typedef struct
{
    volatile U_PERI_MEM_CTRL        PERI_MEM_CTRL                    ; /* 0x0 */
    volatile U_PERI_MEM_CTRL_0      PERI_MEM_CTRL_0                  ; /* 0x4 */
    volatile U_PERI_MEM_CTRL_1      PERI_MEM_CTRL_1                  ; /* 0x8 */
    volatile unsigned int           reserved_0                       ; /* 0xc */
    volatile unsigned int           PERI_GPU_MEM_CTRL                ; /* 0x10 */
    volatile unsigned int           reserved_1[11]                   ; /* 0x14~0x3c */
    volatile unsigned int           PERI_ECO_VERSION                 ; /* 0x40 */
    volatile unsigned int           reserved_2[3]                    ; /* 0x44~0x4c */
    volatile U_PERI_JTAG_CTRL       PERI_JTAG_CTRL                   ; /* 0x50 */
    volatile unsigned int           reserved_3[4]                    ; /* 0x54~0x60 */
    volatile U_PERI_CTRL_1          PERI_CTRL_1                      ; /* 0x64 */
    volatile U_PERI_CTRL_2          PERI_CTRL_2                      ; /* 0x68 */
    volatile unsigned int           reserved_4[21]                   ; /* 0x6c~0xbc */
    volatile U_PERI_DFT_CTRL        PERI_DFT_CTRL                    ; /* 0xc0 */
    volatile unsigned int           reserved_5[3]                    ; /* 0xc4~0xcc */
    volatile unsigned int           PERI_CPU_DFT_DATAIN              ; /* 0xd0 */
    volatile unsigned int           PERI_CPU_DFT_DATAOUT             ; /* 0xd4 */
    volatile unsigned int           reserved_6[2]                    ; /* 0xd8~0xdc */
    volatile U_PERI_CPU_DFT_CTRL0   PERI_CPU_DFT_CTRL0               ; /* 0xe0 */
    volatile U_PERI_CPU_DFT_CTRL1   PERI_CPU_DFT_CTRL1               ; /* 0xe4 */
    volatile U_PERI_CPU_DFT_CTRL2   PERI_CPU_DFT_CTRL2               ; /* 0xe8 */
    volatile unsigned int           reserved_7                       ; /* 0xec */
    volatile U_PERI_GPU_DFT_CTRL    PERI_GPU_DFT_CTRL                ; /* 0xf0 */
    volatile unsigned int           reserved_8                       ; /* 0xf4 */
    volatile U_PERI_NPU_DFT_CTRL    PERI_NPU_DFT_CTRL                ; /* 0xf8 */
    volatile unsigned int           reserved_9                       ; /* 0xfc */
    volatile U_PERI_START_MODE      PERI_START_MODE                  ; /* 0x100 */
    volatile unsigned int           reserved_10[15]                  ; /* 0x104~0x13c */
    volatile unsigned int           PERI_SOC_FUSE_0                  ; /* 0x140 */
    volatile unsigned int           PERI_SOC_FUSE_1                  ; /* 0x144 */
    volatile unsigned int           PERI_SOC_FUSE_2                  ; /* 0x148 */
    volatile unsigned int           PERI_SOC_FUSE_3                  ; /* 0x14c */
    volatile unsigned int           reserved_11[12]                  ; /* 0x150~0x17c */
    volatile U_PERI_CPU_STATE       PERI_CPU_STATE                   ; /* 0x180 */
    volatile unsigned int           reserved_12[31]                  ; /* 0x184~0x1fc */
    volatile U_PERI_QOS_PRO_CFG0    PERI_QOS_PRO_CFG0                ; /* 0x200 */
    volatile unsigned int           reserved_13[3]                   ; /* 0x204~0x20c */
    volatile U_PERI_QOS_SEC_CFG0    PERI_QOS_SEC_CFG0                ; /* 0x210 */
    volatile U_PERI_QOS_SEC_CFG1    PERI_QOS_SEC_CFG1                ; /* 0x214 */
    volatile unsigned int           reserved_14[2]                   ; /* 0x218~0x21c */
    volatile U_PERI_QOS_DDR_CFG0    PERI_QOS_DDR_CFG0                ; /* 0x220 */
    volatile unsigned int           reserved_15[3]                   ; /* 0x224~0x22c */
    volatile U_PERI_QOS_OFFLINE_CFG0   PERI_QOS_OFFLINE_CFG0            ; /* 0x230 */
    volatile U_PERI_QOS_OFFLINE_CFG1   PERI_QOS_OFFLINE_CFG1            ; /* 0x234 */
    volatile unsigned int           reserved_16[2]                   ; /* 0x238~0x23c */
    volatile U_PERI_QOS_ONLINE_CFG0   PERI_QOS_ONLINE_CFG0             ; /* 0x240 */
    volatile U_PERI_QOS_ONLINE_CFG1   PERI_QOS_ONLINE_CFG1             ; /* 0x244 */
    volatile unsigned int           reserved_17[2]                   ; /* 0x248~0x24c */
    volatile U_PERI_QOS_AUDIO_CFG0   PERI_QOS_AUDIO_CFG0              ; /* 0x250 */
    volatile unsigned int           reserved_18[3]                   ; /* 0x254~0x25c */
    volatile U_PERI_QOS_PERI_CFG0   PERI_QOS_PERI_CFG0               ; /* 0x260 */
    volatile U_PERI_QOS_PERI_CFG1   PERI_QOS_PERI_CFG1               ; /* 0x264 */
    volatile U_PERI_QOS_PERI_CFG2   PERI_QOS_PERI_CFG2               ; /* 0x268 */
    volatile U_PERI_QOS_PERI_CFG3   PERI_QOS_PERI_CFG3               ; /* 0x26c */
    volatile unsigned int           reserved_19[4]                   ; /* 0x270~0x27c */
    volatile U_PERI_MMU_QOS         PERI_MMU_QOS                     ; /* 0x280 */
    volatile unsigned int           reserved_20[15]                  ; /* 0x284~0x2bc */
    volatile U_PERI_QOS_MEDIA1_AXI   PERI_QOS_MEDIA1_AXI              ; /* 0x2c0 */
    volatile unsigned int           reserved_21                      ; /* 0x2c4 */
    volatile U_PERI_QOS_MEDIA3_AXI   PERI_QOS_MEDIA3_AXI              ; /* 0x2c8 */
    volatile unsigned int           reserved_22                      ; /* 0x2cc */
    volatile U_PERI_QOS_PERI1_AXI   PERI_QOS_PERI1_AXI               ; /* 0x2d0 */
    volatile U_PERI_QOS_PERI1_SEC_AXI   PERI_QOS_PERI1_SEC_AXI           ; /* 0x2d4 */
    volatile unsigned int           reserved_23[2]                   ; /* 0x2d8~0x2dc */
    volatile U_PERI_QOS_CPU_DDR_AXI   PERI_QOS_CPU_DDR_AXI             ; /* 0x2e0 */
    volatile unsigned int           reserved_24[71]                  ; /* 0x2e4~0x3fc */
    volatile U_PERI_USB2_0_PHY_CTRL0   PERI_USB2_0_PHY_CTRL0            ; /* 0x400 */
    volatile U_PERI_USB2_0_PHY_CTRL1   PERI_USB2_0_PHY_CTRL1            ; /* 0x404 */
    volatile U_PERI_USB2_0_PHY_CTRL2   PERI_USB2_0_PHY_CTRL2            ; /* 0x408 */
    volatile unsigned int           reserved_25                      ; /* 0x40c */
    volatile U_PERI_USB2_1_PHY_CTRL0   PERI_USB2_1_PHY_CTRL0            ; /* 0x410 */
    volatile U_PERI_USB2_1_PHY_CTRL1   PERI_USB2_1_PHY_CTRL1            ; /* 0x414 */
    volatile U_PERI_USB2_1_PHY_CTRL2   PERI_USB2_1_PHY_CTRL2            ; /* 0x418 */
    volatile unsigned int           reserved_26[5]                   ; /* 0x41c~0x42c */
    volatile U_PERI_USB3_1_PHY_CTRL0   PERI_USB3_1_PHY_CTRL0            ; /* 0x430 */
    volatile U_PERI_USB3_1_PHY_CTRL1   PERI_USB3_1_PHY_CTRL1            ; /* 0x434 */
    volatile U_PERI_USB3_1_PHY_CTRL2   PERI_USB3_1_PHY_CTRL2            ; /* 0x438 */
    volatile unsigned int           reserved_27[23]                  ; /* 0x43c~0x494 */
    volatile U_PERI_COMBPHY1_STATE   PERI_COMBPHY1_STATE              ; /* 0x498 */
    volatile unsigned int           reserved_28[5]                   ; /* 0x49c~0x4ac */
    volatile U_PERI_COMBPHY2_CFG0   PERI_COMBPHY2_CFG0               ; /* 0x4b0 */
    volatile U_PERI_COMBPHY2_STATE0   PERI_COMBPHY2_STATE0             ; /* 0x4b4 */
    volatile unsigned int           reserved_29[2]                   ; /* 0x4b8~0x4bc */
    volatile U_PERI_COMBPHY2_CFG1   PERI_COMBPHY2_CFG1               ; /* 0x4c0 */
    volatile U_PERI_COMBPHY2_STATE1   PERI_COMBPHY2_STATE1             ; /* 0x4c4 */
    volatile unsigned int           reserved_30[2]                   ; /* 0x4c8~0x4cc */
    volatile U_PERI_COMBPHY2_CFG2   PERI_COMBPHY2_CFG2               ; /* 0x4d0 */
    volatile U_PERI_COMBPHY2_STATE2   PERI_COMBPHY2_STATE2             ; /* 0x4d4 */
    volatile U_PERI_PCIE0_IO_CFG    PERI_PCIE0_IO_CFG                ; /* 0x4d8 */
    volatile unsigned int           reserved_31                      ; /* 0x4dc */
    volatile U_PERI_COMBPHY2_CFG3   PERI_COMBPHY2_CFG3               ; /* 0x4e0 */
    volatile U_PERI_COMBPHY2_STATE3   PERI_COMBPHY2_STATE3             ; /* 0x4e4 */
    volatile U_PERI_PCIE1_IO_CFG    PERI_PCIE1_IO_CFG                ; /* 0x4e8 */
    volatile unsigned int           reserved_32[69]                  ; /* 0x4ec~0x5fc */
    volatile unsigned int           PERI_USB2_CTRL_CFG0              ; /* 0x600 */
    volatile unsigned int           reserved_33[3]                   ; /* 0x604~0x60c */
    volatile unsigned int           PERI_USB2_CTRL_CFG1              ; /* 0x610 */
    volatile unsigned int           reserved_34[11]                  ; /* 0x614~0x63c */
    volatile unsigned int           PERI_USB31_CTRL_CFG1             ; /* 0x640 */
    volatile unsigned int           reserved_35                      ; /* 0x644 */
    volatile unsigned int           PERI_USB31_SOC_BW_CFG1           ; /* 0x648 */
    volatile unsigned int           reserved_36[173]                 ; /* 0x64c~0x8fc */
    volatile U_PERI_USB_RESUME_INT_MASK   PERI_USB_RESUME_INT_MASK         ; /* 0x900 */
    volatile U_PERI_USB_RESUME_INT_RAWSTAT   PERI_USB_RESUME_INT_RAWSTAT      ; /* 0x904 */
    volatile U_PERI_USB_RESUME_INT_STAT   PERI_USB_RESUME_INT_STAT         ; /* 0x908 */
    volatile unsigned int           reserved_37[93]                  ; /* 0x90c~0xa7c */
    volatile U_PERI_PWR_SW_CTRL     PERI_PWR_SW_CTRL                 ; /* 0xa80 */
    volatile unsigned int           reserved_38[63]                  ; /* 0xa84~0xb7c */
    volatile U_PERI_POWER_SEL       PERI_POWER_SEL                   ; /* 0xb80 */
    volatile U_PERI_INTF_IO_SEL     PERI_INTF_IO_SEL                 ; /* 0xb84 */
    volatile unsigned int           reserved_39[30]                  ; /* 0xb88~0xbfc */
    volatile unsigned int           PERI_GPU_TEXFMTENABLE            ; /* 0xc00 */
    volatile unsigned int           reserved_40                      ; /* 0xc04 */
    volatile U_PERI_GPU_STRIP_CTRL   PERI_GPU_STRIP_CTRL              ; /* 0xc08 */
    volatile unsigned int           reserved_41[29]                  ; /* 0xc0c~0xc7c */
    volatile U_PERI_NPU_CTRL        PERI_NPU_CTRL                    ; /* 0xc80 */
    volatile unsigned int           PERI_NPU_CTRL0                   ; /* 0xc84 */
    volatile unsigned int           PERI_NPU_CTRL1                   ; /* 0xc88 */
    volatile unsigned int           reserved_42[5]                   ; /* 0xc8c~0xc9c */
    volatile U_PERI_NPU_STATE       PERI_NPU_STATE                   ; /* 0xca0 */
    volatile unsigned int           PERI_NPU_STAT0                   ; /* 0xca4 */
    volatile unsigned int           PERI_NPU_STAT1                   ; /* 0xca8 */
    volatile unsigned int           reserved_43[21]                  ; /* 0xcac~0xcfc */
    volatile unsigned int           PERI_HDMIRX_AON_CTRL             ; /* 0xd00 */
    volatile unsigned int           PERI_HDMIRX_AON_STAT             ; /* 0xd04 */
    volatile unsigned int           reserved_44[6]                   ; /* 0xd08~0xd1c */
    volatile unsigned int           PERI_HDMIRX_PWD_CTRL             ; /* 0xd20 */
    volatile unsigned int           PERI_HDMIRX_PWD_STAT             ; /* 0xd24 */
    volatile unsigned int           reserved_45[22]                  ; /* 0xd28~0xd7c */
    volatile U_PERI_HDMITX_CTRL     PERI_HDMITX_CTRL                 ; /* 0xd80 */
    volatile unsigned int           reserved_46[31]                  ; /* 0xd84~0xdfc */
    volatile U_PERI_SOFT_INT        PERI_SOFT_INT                    ; /* 0xe00 */
    volatile unsigned int           reserved_47[3]                   ; /* 0xe04~0xe0c */
    volatile U_PERI_SOFT_INT_MASK   PERI_SOFT_INT_MASK               ; /* 0xe10 */
    volatile unsigned int           reserved_48[59]                  ; /* 0xe14~0xefc */
    volatile unsigned int           PERI_SW_SET                      ; /* 0xf00 */

} S_PERICTRL_REGS_TYPE;

#endif /* __HI_REG_PERI_H__ */
