/*
 * Copyright (C) Hisilicon Technologies Co., Ltd. 2019. All rights reserved.
 * Description:
 * Author: Automatic generated by nManager v4.0
 * Create: 2019-06-28
 */

#ifndef __HI_REG_SYS_H__
#define __HI_REG_SYS_H__

/* Define the union U_SC_MEM_CTRL */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    reserved_0            : 26  ; /* [25..0]  */
        unsigned int    sys_mem_ctrl_lock     : 1   ; /* [26]  */
        unsigned int    reserved_1            : 4   ; /* [30..27]  */
        unsigned int    sys_ram_ck_gt_en      : 1   ; /* [31]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_MEM_CTRL;

/* Define the union U_SC_MEM_CTRL_0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_rfs_ema           : 3   ; /* [2..0]  */
        unsigned int    sys_rfs_emaw          : 2   ; /* [4..3]  */
        unsigned int    sys_rfs_rme           : 1   ; /* [5]  */
        unsigned int    sys_rfs_rm            : 4   ; /* [9..6]  */
        unsigned int    reserved_0            : 6   ; /* [15..10]  */
        unsigned int    sys_ras_ema           : 3   ; /* [18..16]  */
        unsigned int    sys_ras_emaw          : 2   ; /* [20..19]  */
        unsigned int    sys_ras_rme           : 1   ; /* [21]  */
        unsigned int    sys_ras_rm            : 4   ; /* [25..22]  */
        unsigned int    reserved_1            : 6   ; /* [31..26]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_MEM_CTRL_0;

/* Define the union U_SC_MEM_CTRL_1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_rft_emaa          : 3   ; /* [2..0]  */
        unsigned int    sys_rft_emab          : 3   ; /* [5..3]  */
        unsigned int    sys_rft_emasa         : 1   ; /* [6]  */
        unsigned int    sys_rft_colldisn      : 1   ; /* [7]  */
        unsigned int    sys_rft_rmea          : 1   ; /* [8]  */
        unsigned int    sys_rft_rma           : 4   ; /* [12..9]  */
        unsigned int    sys_rft_rmeb          : 1   ; /* [13]  */
        unsigned int    sys_rft_rmb           : 4   ; /* [17..14]  */
        unsigned int    reserved_0            : 6   ; /* [23..18]  */
        unsigned int    sys_ros_ema           : 3   ; /* [26..24]  */
        unsigned int    sys_ros_rme           : 1   ; /* [27]  */
        unsigned int    sys_ros_rm            : 4   ; /* [31..28]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_MEM_CTRL_1;

/* Define the union U_SC_WDG_RST_CTRL */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_wdg_rst_ctrl      : 1   ; /* [0]  */
        unsigned int    reserved_0            : 31  ; /* [31..1]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_WDG_RST_CTRL;

/* Define the union U_SC_MCU_STATE */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_mcu_pc            : 16  ; /* [15..0]  */
        unsigned int    reserved_0            : 16  ; /* [31..16]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_MCU_STATE;

/* Define the union U_SC_CRG_CTRL_0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    mcu_bus_pclk_sel      : 1   ; /* [0]  */
        unsigned int    reserved_0            : 3   ; /* [3..1]  */
        unsigned int    mcu_bus_hclk_sel      : 1   ; /* [4]  */
        unsigned int    reserved_1            : 11  ; /* [15..5]  */
        unsigned int    lpmcu_core_srst_req   : 1   ; /* [16]  */
        unsigned int    lpmcu_cken            : 1   ; /* [17]  */
        unsigned int    sc_ctrl               : 14  ; /* [31..18]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_CRG_CTRL_0;

/* Define the union U_SC_CRG_CTRL_1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    reserved_0            : 4   ; /* [3..0]  */
        unsigned int    ir_cken               : 1   ; /* [4]  */
        unsigned int    ir_srst_req           : 1   ; /* [5]  */
        unsigned int    led_cken              : 1   ; /* [6]  */
        unsigned int    led_srst_req          : 1   ; /* [7]  */
        unsigned int    timer_cken            : 1   ; /* [8]  */
        unsigned int    timer_srst_req        : 1   ; /* [9]  */
        unsigned int    reserved_1            : 2   ; /* [11..10]  */
        unsigned int    lsadc_cken            : 1   ; /* [12]  */
        unsigned int    lsadc_srst_req        : 1   ; /* [13]  */
        unsigned int    reserved_2            : 2   ; /* [15..14]  */
        unsigned int    uart_cken             : 1   ; /* [16]  */
        unsigned int    uart_srst_req         : 1   ; /* [17]  */
        unsigned int    reserved_3            : 6   ; /* [23..18]  */
        unsigned int    i2c0_cken             : 1   ; /* [24]  */
        unsigned int    i2c0_srst_req         : 1   ; /* [25]  */
        unsigned int    i2c1_cken             : 1   ; /* [26]  */
        unsigned int    i2c1_srst_req         : 1   ; /* [27]  */
        unsigned int    reserved_4            : 4   ; /* [31..28]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_CRG_CTRL_1;

/* Define the union U_SC_CRG_CTRL_2 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    hdmitx_ctrl_cec_cken  : 1   ; /* [0]  */
        unsigned int    hdmitx_ctrl_cec_srst_req : 1   ; /* [1]  */
        unsigned int    reserved_0            : 2   ; /* [3..2]  */
        unsigned int    hdmitx_aon_osc_cken   : 1   ; /* [4]  */
        unsigned int    hdmitx_aon_srst_req   : 1   ; /* [5]  */
        unsigned int    hdmitx_aon_apb_cken   : 1   ; /* [6]  */
        unsigned int    hdmitx_aon_bus_srst_req : 1   ; /* [7]  */
        unsigned int    reserved_1            : 8   ; /* [15..8]  */
        unsigned int    hdmirx_2p1_aon_cken   : 1   ; /* [16]  */
        unsigned int    hdmirx_2p1_aon_srst_req : 1   ; /* [17]  */
        unsigned int    hdmirx_2p1_aon_apb_srst_req : 1   ; /* [18]  */
        unsigned int    reserved_2            : 13  ; /* [31..19]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_CRG_CTRL_2;

/* Define the union U_SC_CRG_CTRL_3 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_fsensor_srst_req  : 1   ; /* [0]  */
        unsigned int    reserved_0            : 31  ; /* [31..1]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_CRG_CTRL_3;

/* Define the union U_SC_AIDSP_CRG_0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_aidsp0_clk_sel    : 2   ; /* [1..0]  */
        unsigned int    sys_aidsp0_axi_clk_sel : 2   ; /* [3..2]  */
        unsigned int    sys_aidsp0_apb_clk_sel : 2   ; /* [5..4]  */
        unsigned int    reserved_0            : 2   ; /* [7..6]  */
        unsigned int    sys_ocram_work_cksel  : 1   ; /* [8]  */
        unsigned int    sys_ocram_cken        : 1   ; /* [9]  */
        unsigned int    reserved_1            : 6   ; /* [15..10]  */
        unsigned int    sys_dsp0_cken         : 1   ; /* [16]  */
        unsigned int    sys_dsp0_srst_req     : 1   ; /* [17]  */
        unsigned int    sys_dsp0_debug_srst_req : 1   ; /* [18]  */
        unsigned int    sys_dsp0_mmu_cken     : 1   ; /* [19]  */
        unsigned int    sys_dsp0_mmu_srst_req : 1   ; /* [20]  */
        unsigned int    reserved_2            : 11  ; /* [31..21]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_AIDSP_CRG_0;

/* Define the union U_SC_AIDSP_CRG_1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_aiaoclk_skipcfg   : 5   ; /* [4..0]  */
        unsigned int    sys_aiaoclk_loaden    : 1   ; /* [5]  */
        unsigned int    sys_aiao_mclk_sel     : 1   ; /* [6]  */
        unsigned int    sys_aiao_work_cksel   : 1   ; /* [7]  */
        unsigned int    sys_dmic_srst_req     : 1   ; /* [8]  */
        unsigned int    sys_dmic_cken         : 1   ; /* [9]  */
        unsigned int    sys_dmic_clk_sel      : 1   ; /* [10]  */
        unsigned int    reserved_0            : 5   ; /* [15..11]  */
        unsigned int    sys_mad_cken          : 1   ; /* [16]  */
        unsigned int    sys_mad_srst_req      : 1   ; /* [17]  */
        unsigned int    sys_mad_work_cksel    : 1   ; /* [18]  */
        unsigned int    sys_mad_clk_sel       : 1   ; /* [19]  */
        unsigned int    reserved_1            : 12  ; /* [31..20]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_AIDSP_CRG_1;

/* Define the union U_SC_CRG_PLL_0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    epll_ctrl0            : 31  ; /* [30..0]  */
        unsigned int    reserved_0            : 1   ; /* [31]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_CRG_PLL_0;

/* Define the union U_SC_CRG_PLL_1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    epll_ctrl1            : 30  ; /* [29..0]  */
        unsigned int    reserved_0            : 2   ; /* [31..30]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_CRG_PLL_1;

/* Define the union U_SC_CRG_PLL_2 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    epll_ctrl2            : 30  ; /* [29..0]  */
        unsigned int    reserved_0            : 2   ; /* [31..30]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_CRG_PLL_2;

/* Define the union U_SC_CRG_PLL_3 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    epll_ssmod_ctrl       : 14  ; /* [13..0]  */
        unsigned int    reserved_0            : 18  ; /* [31..14]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_CRG_PLL_3;

/* Define the union U_SC_CRG_PLL_4 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    epll_tune_int_cfg     : 12  ; /* [11..0]  */
        unsigned int    reserved_0            : 20  ; /* [31..12]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_CRG_PLL_4;

/* Define the union U_SC_CRG_PLL_5 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    epll_tune_frac_cfg    : 24  ; /* [23..0]  */
        unsigned int    reserved_0            : 8   ; /* [31..24]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_CRG_PLL_5;

/* Define the union U_SC_CRG_PLL_6 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    epll_tune_step_int    : 12  ; /* [11..0]  */
        unsigned int    reserved_0            : 20  ; /* [31..12]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_CRG_PLL_6;

/* Define the union U_SC_CRG_PLL_7 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    epll_tune_step_frac   : 24  ; /* [23..0]  */
        unsigned int    reserved_0            : 8   ; /* [31..24]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_CRG_PLL_7;

/* Define the union U_SC_CRG_PLL_8 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    epll_tune_cken        : 1   ; /* [0]  */
        unsigned int    epll_tune_srst_req    : 1   ; /* [1]  */
        unsigned int    epll_tune_mode        : 1   ; /* [2]  */
        unsigned int    epll_tune_en          : 1   ; /* [3]  */
        unsigned int    epll_tune_divval      : 4   ; /* [7..4]  */
        unsigned int    epll_tune_soft_cfg    : 1   ; /* [8]  */
        unsigned int    reserved_0            : 23  ; /* [31..9]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_CRG_PLL_8;

/* Define the union U_SC_CRG_PLL_9 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    epll_tune_int         : 12  ; /* [11..0]  */
        unsigned int    epll_tune_sw_ok       : 1   ; /* [12]  */
        unsigned int    epll_tune_busy        : 1   ; /* [13]  */
        unsigned int    reserved_0            : 18  ; /* [31..14]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_CRG_PLL_9;

/* Define the union U_SC_CRG_PLL_10 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    epll_tune_frac        : 24  ; /* [23..0]  */
        unsigned int    reserved_0            : 8   ; /* [31..24]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_CRG_PLL_10;

/* Define the union U_SC_CRG_PLL_11 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    epll_test_calout      : 12  ; /* [11..0]  */
        unsigned int    reserved_0            : 4   ; /* [15..12]  */
        unsigned int    epll_offsetcalout     : 12  ; /* [27..16]  */
        unsigned int    reserved_1            : 4   ; /* [31..28]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_CRG_PLL_11;

/* Define the union U_SC_CRG_PLL_12 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    epll_lock_cnt         : 4   ; /* [3..0]  */
        unsigned int    reserved_0            : 28  ; /* [31..4]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_CRG_PLL_12;

/* Define the union U_SC_POWER_STAT */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_power_state       : 1   ; /* [0]  */
        unsigned int    reserved_0            : 31  ; /* [31..1]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_POWER_STAT;

/* Define the union U_SC_LOW_POWER_STAT */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_bus_discon_timeout_clr : 1   ; /* [0]  */
        unsigned int    reserved_0            : 2   ; /* [2..1]  */
        unsigned int    mcu_lp_subsys_iso     : 1   ; /* [3]  */
        unsigned int    sys_power_status      : 4   ; /* [7..4]  */
        unsigned int    reserved_1            : 8   ; /* [15..8]  */
        unsigned int    sys_cluster0_standbywfi : 4   ; /* [19..16]  */
        unsigned int    sys_cluster0_standbywfil2 : 1   ; /* [20]  */
        unsigned int    reserved_2            : 3   ; /* [23..21]  */
        unsigned int    sys_cluster1_standbywfi : 4   ; /* [27..24]  */
        unsigned int    sys_cluster1_standbywfil2 : 1   ; /* [28]  */
        unsigned int    reserved_3            : 3   ; /* [31..29]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_LOW_POWER_STAT;

/* Define the union U_SC_DDRPHY_LP_EN */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_ddrphy0_lp_en     : 2   ; /* [1..0]  */
        unsigned int    reserved_0            : 30  ; /* [31..2]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_DDRPHY_LP_EN;

/* Define the union U_SC_AIDSP_PWRUP_CTRL */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_aidsp_pd_srst_req : 1   ; /* [0]  */
        unsigned int    reserved_0            : 7   ; /* [7..1]  */
        unsigned int    sys_aidsp_pwrup       : 1   ; /* [8]  */
        unsigned int    reserved_1            : 7   ; /* [15..9]  */
        unsigned int    sys_aidsp_iso         : 1   ; /* [16]  */
        unsigned int    reserved_2            : 15  ; /* [31..17]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_AIDSP_PWRUP_CTRL;

/* Define the union U_SC_AIDSP_PWRUP_STAT */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_aidsp_pwrup_ack   : 1   ; /* [0]  */
        unsigned int    reserved_0            : 31  ; /* [31..1]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_AIDSP_PWRUP_STAT;

/* Define the union U_SC_HPM0_CTRL0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_hpm_div           : 6   ; /* [5..0]  */
        unsigned int    reserved_0            : 2   ; /* [7..6]  */
        unsigned int    sys_hpm_shift         : 2   ; /* [9..8]  */
        unsigned int    reserved_1            : 2   ; /* [11..10]  */
        unsigned int    sys_hpm_offset        : 10  ; /* [21..12]  */
        unsigned int    reserved_2            : 2   ; /* [23..22]  */
        unsigned int    sys_hpm_en            : 1   ; /* [24]  */
        unsigned int    sys_hpm_bypass        : 1   ; /* [25]  */
        unsigned int    sys_hpm_monitor_en    : 1   ; /* [26]  */
        unsigned int    reserved_3            : 5   ; /* [31..27]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_HPM0_CTRL0;

/* Define the union U_SC_HPM0_CTRL1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_hpm_pc_record0    : 10  ; /* [9..0]  */
        unsigned int    sys_hpm_pc_valid      : 1   ; /* [10]  */
        unsigned int    reserved_0            : 1   ; /* [11]  */
        unsigned int    sys_hpm_pc_record1    : 10  ; /* [21..12]  */
        unsigned int    reserved_1            : 2   ; /* [23..22]  */
        unsigned int    sys_hpm_low_warning   : 1   ; /* [24]  */
        unsigned int    sys_hpm_up_warning    : 1   ; /* [25]  */
        unsigned int    reserved_2            : 6   ; /* [31..26]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_HPM0_CTRL1;

/* Define the union U_SC_HPM0_CTRL2 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_hpm_pc_record2    : 10  ; /* [9..0]  */
        unsigned int    reserved_0            : 2   ; /* [11..10]  */
        unsigned int    sys_hpm_pc_record3    : 10  ; /* [21..12]  */
        unsigned int    sys_hpm_rcc           : 10  ; /* [31..22]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_HPM0_CTRL2;

/* Define the union U_SC_HPM0_CTRL3 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_hpm_uplimit       : 10  ; /* [9..0]  */
        unsigned int    reserved_0            : 2   ; /* [11..10]  */
        unsigned int    sys_hpm_lowlimit      : 10  ; /* [21..12]  */
        unsigned int    reserved_1            : 2   ; /* [23..22]  */
        unsigned int    sys_hpm_monitor_period : 8   ; /* [31..24]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_HPM0_CTRL3;

/* Define the union U_SC_HPM0_CTRL4 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_hpm_monitor_period_fine : 8   ; /* [7..0]  */
        unsigned int    reserved_0            : 24  ; /* [31..8]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_HPM0_CTRL4;

/* Define the union U_SC_SHPM0_CTRL0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_shpm_cfg          : 16  ; /* [15..0]  */
        unsigned int    reserved_0            : 16  ; /* [31..16]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_SHPM0_CTRL0;

/* Define the union U_SC_SHPM0_CTRL1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_shpm_record       : 17  ; /* [16..0]  */
        unsigned int    reserved_0            : 15  ; /* [31..17]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_SHPM0_CTRL1;

/* Define the union U_SC_PWM_CTRL0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_pwm_enable        : 1   ; /* [0]  */
        unsigned int    sys_pwm_inv           : 1   ; /* [1]  */
        unsigned int    reserved_0            : 30  ; /* [31..2]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_PWM_CTRL0;

/* Define the union U_SC_PWM_CTRL1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_pwm_duty_limit_en : 1   ; /* [0]  */
        unsigned int    reserved_0            : 31  ; /* [31..1]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_PWM_CTRL1;

/* Define the union U_SC_PWM_CTRL2 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_pwm_period        : 16  ; /* [15..0]  */
        unsigned int    sys_pwm_duty          : 16  ; /* [31..16]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_PWM_CTRL2;

/* Define the union U_SC_CACHE_SIZE_CFG */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_cluster0_l2_cache_size_cfg : 2   ; /* [1..0]  */
        unsigned int    reserved_0            : 6   ; /* [7..2]  */
        unsigned int    sys_cluster0_l1_dcache_size_cfg : 1   ; /* [8]  */
        unsigned int    reserved_1            : 7   ; /* [15..9]  */
        unsigned int    sys_cluster1_l2_cache_size_cfg : 2   ; /* [17..16]  */
        unsigned int    reserved_2            : 6   ; /* [23..18]  */
        unsigned int    sys_cluster1_l1_dcache_size_cfg : 1   ; /* [24]  */
        unsigned int    reserved_3            : 7   ; /* [31..25]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_CACHE_SIZE_CFG;

/* Define the union U_SC_DOLBY_CTRL */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_dolby_gen_lock    : 1   ; /* [0]  */
        unsigned int    reserved_0            : 31  ; /* [31..1]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_DOLBY_CTRL;

/* Define the union U_SC_MCU_LDO_CTRL */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_mcu_ldo_vset      : 4   ; /* [3..0]  */
        unsigned int    reserved_0            : 4   ; /* [7..4]  */
        unsigned int    sys_mcu_ldo_enz       : 1   ; /* [8]  */
        unsigned int    sys_mcu_ldo_en_lp     : 1   ; /* [9]  */
        unsigned int    reserved_1            : 22  ; /* [31..10]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_MCU_LDO_CTRL;

/* Define the union U_SC_MCU_LDO_STAT */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_mcu_ldo_ocp       : 1   ; /* [0]  */
        unsigned int    reserved_0            : 31  ; /* [31..1]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_MCU_LDO_STAT;

/* Define the union U_SC_LSADC_CTRL */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_lsadc_en_a        : 1   ; /* [0]  */
        unsigned int    sys_lsadc_en_b        : 1   ; /* [1]  */
        unsigned int    sys_lsadc_en_c        : 1   ; /* [2]  */
        unsigned int    sys_lsadc_en_d        : 1   ; /* [3]  */
        unsigned int    sys_lsadc_reg         : 4   ; /* [7..4]  */
        unsigned int    sys_lsadc_sarreg2     : 2   ; /* [9..8]  */
        unsigned int    reserved_0            : 2   ; /* [11..10]  */
        unsigned int    sys_lsadc_sarreg1     : 2   ; /* [13..12]  */
        unsigned int    reserved_1            : 18  ; /* [31..14]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_LSADC_CTRL;

/* Define the union U_SC_LSADC_DATA */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_lsadc_rdata_a     : 10  ; /* [9..0]  */
        unsigned int    reserved_0            : 6   ; /* [15..10]  */
        unsigned int    sys_lsadc_rdata_b     : 10  ; /* [25..16]  */
        unsigned int    reserved_1            : 6   ; /* [31..26]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_LSADC_DATA;

/* Define the union U_SC_LSADC_DATA1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_lsadc_rdata_c     : 10  ; /* [9..0]  */
        unsigned int    reserved_0            : 6   ; /* [15..10]  */
        unsigned int    sys_lsadc_rdata_d     : 10  ; /* [25..16]  */
        unsigned int    reserved_1            : 6   ; /* [31..26]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_LSADC_DATA1;

/* Define the union U_SC_MEM_REPAIR_CTRL2 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_repair_clk_sel    : 1   ; /* [0]  */
        unsigned int    reserved_0            : 31  ; /* [31..1]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_MEM_REPAIR_CTRL2;

/* Define the union U_SC_MEM_REPAIR_STAT */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_mrb_load_done     : 1   ; /* [0]  */
        unsigned int    reserved_0            : 31  ; /* [31..1]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_MEM_REPAIR_STAT;

/* Define the union U_SC_FSENSOR_CTRL0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    fsensor_ana_mode      : 1   ; /* [0]  */
        unsigned int    fsensor_func_trim_mode : 1   ; /* [1]  */
        unsigned int    reserved_0            : 6   ; /* [7..2]  */
        unsigned int    fsensor_detect_start  : 1   ; /* [8]  */
        unsigned int    fsensor_trim_start    : 1   ; /* [9]  */
        unsigned int    reserved_1            : 6   ; /* [15..10]  */
        unsigned int    fsensor_period_detect_cfg : 2   ; /* [17..16]  */
        unsigned int    reserved_2            : 6   ; /* [23..18]  */
        unsigned int    fsensor_freq_detect_cfg : 2   ; /* [25..24]  */
        unsigned int    reserved_3            : 6   ; /* [31..26]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_FSENSOR_CTRL0;

/* Define the union U_SC_FSENSOR_CTRL1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    fsensor_freq_trim_code_in : 13  ; /* [12..0]  */
        unsigned int    reserved_0            : 3   ; /* [15..13]  */
        unsigned int    fsensor_duty_trim_code_in : 10  ; /* [25..16]  */
        unsigned int    reserved_1            : 6   ; /* [31..26]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_FSENSOR_CTRL1;

/* Define the union U_SC_FSENSOR_STATE0 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    fsensor_alarm_freq    : 1   ; /* [0]  */
        unsigned int    fsensor_alarm_duty    : 1   ; /* [1]  */
        unsigned int    fsensor_alarm_glitch  : 1   ; /* [2]  */
        unsigned int    fsensor_trim_done     : 1   ; /* [3]  */
        unsigned int    reserved_0            : 28  ; /* [31..4]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_FSENSOR_STATE0;

/* Define the union U_SC_FSENSOR_STATE1 */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    fsensor_freq_trim_code_out : 13  ; /* [12..0]  */
        unsigned int    reserved_0            : 3   ; /* [15..13]  */
        unsigned int    fsensor_duty_trim_code_out : 10  ; /* [25..16]  */
        unsigned int    reserved_1            : 6   ; /* [31..26]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_FSENSOR_STATE1;

/* Define the union U_SC_INTF_IO_SEL */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_hdmirx1_i2c_sel   : 2   ; /* [1..0]  */
        unsigned int    reserved_0            : 6   ; /* [7..2]  */
        unsigned int    sys_hdmitx1_i2c_sel   : 2   ; /* [9..8]  */
        unsigned int    reserved_1            : 22  ; /* [31..10]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_INTF_IO_SEL;

/* Define the union U_SC_GPIO_IO_SEL */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_lsadc0_gpio_sel   : 1   ; /* [0]  */
        unsigned int    sys_lsadc1_gpio_sel   : 1   ; /* [1]  */
        unsigned int    sys_lsadc2_gpio_sel   : 1   ; /* [2]  */
        unsigned int    sys_lsadc3_gpio_sel   : 1   ; /* [3]  */
        unsigned int    reserved_0            : 28  ; /* [31..4]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_GPIO_IO_SEL;

/* Define the union U_SC_SOFT_INT */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_int_mce2arm       : 1   ; /* [0]  */
        unsigned int    sys_int_mcu2aidsp     : 1   ; /* [1]  */
        unsigned int    sys_int_cpu2aidsp     : 1   ; /* [2]  */
        unsigned int    reserved_0            : 29  ; /* [31..3]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_SOFT_INT;

/* Define the union U_SC_SOFT_INT_MASK */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_int_mce2arm_mask  : 1   ; /* [0]  */
        unsigned int    sys_int_mcu2aidsp_mask : 1   ; /* [1]  */
        unsigned int    sys_int_cpu2aidsp_mask : 1   ; /* [2]  */
        unsigned int    reserved_0            : 29  ; /* [31..3]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_SOFT_INT_MASK;

/* Define the union U_SC_INT_STATE */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    int_aon_gpio0         : 1   ; /* [0]  */
        unsigned int    int_aon_gpio1         : 1   ; /* [1]  */
        unsigned int    int_aon_gpio2         : 1   ; /* [2]  */
        unsigned int    int_aon_gpio3         : 1   ; /* [3]  */
        unsigned int    int_aon_gpio4         : 1   ; /* [4]  */
        unsigned int    reserved_0            : 11  ; /* [15..5]  */
        unsigned int    int_aon_i2c0          : 1   ; /* [16]  */
        unsigned int    int_aon_i2c1          : 1   ; /* [17]  */
        unsigned int    reserved_1            : 14  ; /* [31..18]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_INT_STATE;

/* Define the union U_SC_AIDSP_INT_MASK */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_aidsp_idle_int_mask : 1   ; /* [0]  */
        unsigned int    reserved_0            : 31  ; /* [31..1]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_AIDSP_INT_MASK;

/* Define the union U_SC_AIDSP_INT_CLR */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_aidsp_idle_int_clr : 1   ; /* [0]  */
        unsigned int    reserved_0            : 31  ; /* [31..1]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_AIDSP_INT_CLR;

/* Define the union U_SC_AIDSP_INT_STATE */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_aidsp_idle_int    : 1   ; /* [0]  */
        unsigned int    reserved_0            : 31  ; /* [31..1]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_AIDSP_INT_STATE;

/* Define the union U_SC_AIDSP_INT_MASK_STATE */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sys_aidsp_idle_mask_int : 1   ; /* [0]  */
        unsigned int    reserved_0            : 31  ; /* [31..1]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_AIDSP_INT_MASK_STATE;

/* Define the union U_SC_INT_COUNT_STATE */
typedef union
{
    /* Define the struct bits */
    struct
    {
        unsigned int    sec_hard_rst_cnt      : 4   ; /* [3..0]  */
        unsigned int    vmcu_wdg_rst_cnt      : 4   ; /* [7..4]  */
        unsigned int    ecs_wdg0_rst_cnt      : 4   ; /* [11..8]  */
        unsigned int    aon_wdog_rst_cnt      : 4   ; /* [15..12]  */
        unsigned int    ddrca_hard_rst_cnt    : 4   ; /* [19..16]  */
        unsigned int    timer_hard_rst_cnt    : 4   ; /* [23..20]  */
        unsigned int    sec_srst_cnt          : 4   ; /* [27..24]  */
        unsigned int    sys_srst_cnt          : 4   ; /* [31..28]  */
    } bits;

    /* Define an unsigned member */
    unsigned int    u32;

} U_SC_INT_COUNT_STATE;

//==============================================================================
/* Define the global struct */
typedef struct
{
    volatile U_SC_MEM_CTRL          SC_MEM_CTRL                      ; /* 0x0 */
    volatile U_SC_MEM_CTRL_0        SC_MEM_CTRL_0                    ; /* 0x4 */
    volatile U_SC_MEM_CTRL_1        SC_MEM_CTRL_1                    ; /* 0x8 */
    volatile unsigned int           reserved_0                       ; /* 0xc */
    volatile unsigned int           SC_SYSID                         ; /* 0x10 */
    volatile unsigned int           reserved_1[3]                    ; /* 0x14~0x1c */
    volatile unsigned int           SC_LOCKEN                        ; /* 0x20 */
    volatile unsigned int           reserved_2[7]                    ; /* 0x24~0x3c */
    volatile unsigned int           SC_SYSRES                        ; /* 0x40 */
    volatile U_SC_WDG_RST_CTRL      SC_WDG_RST_CTRL                  ; /* 0x44 */
    volatile unsigned int           reserved_3                       ; /* 0x48 */
    volatile U_SC_MCU_STATE         SC_MCU_STATE                     ; /* 0x4c */
    volatile U_SC_CRG_CTRL_0        SC_CRG_CTRL_0                    ; /* 0x50 */
    volatile unsigned int           reserved_4[3]                    ; /* 0x54~0x5c */
    volatile U_SC_CRG_CTRL_1        SC_CRG_CTRL_1                    ; /* 0x60 */
    volatile U_SC_CRG_CTRL_2        SC_CRG_CTRL_2                    ; /* 0x64 */
    volatile U_SC_CRG_CTRL_3        SC_CRG_CTRL_3                    ; /* 0x68 */
    volatile unsigned int           reserved_5                       ; /* 0x6c */
    volatile U_SC_AIDSP_CRG_0       SC_AIDSP_CRG_0                   ; /* 0x70 */
    volatile U_SC_AIDSP_CRG_1       SC_AIDSP_CRG_1                   ; /* 0x74 */
    volatile unsigned int           reserved_6[2]                    ; /* 0x78~0x7c */
    volatile U_SC_CRG_PLL_0         SC_CRG_PLL_0                     ; /* 0x80 */
    volatile U_SC_CRG_PLL_1         SC_CRG_PLL_1                     ; /* 0x84 */
    volatile U_SC_CRG_PLL_2         SC_CRG_PLL_2                     ; /* 0x88 */
    volatile U_SC_CRG_PLL_3         SC_CRG_PLL_3                     ; /* 0x8c */
    volatile U_SC_CRG_PLL_4         SC_CRG_PLL_4                     ; /* 0x90 */
    volatile U_SC_CRG_PLL_5         SC_CRG_PLL_5                     ; /* 0x94 */
    volatile U_SC_CRG_PLL_6         SC_CRG_PLL_6                     ; /* 0x98 */
    volatile U_SC_CRG_PLL_7         SC_CRG_PLL_7                     ; /* 0x9c */
    volatile U_SC_CRG_PLL_8         SC_CRG_PLL_8                     ; /* 0xa0 */
    volatile U_SC_CRG_PLL_9         SC_CRG_PLL_9                     ; /* 0xa4 */
    volatile U_SC_CRG_PLL_10        SC_CRG_PLL_10                    ; /* 0xa8 */
    volatile U_SC_CRG_PLL_11        SC_CRG_PLL_11                    ; /* 0xac */
    volatile U_SC_CRG_PLL_12        SC_CRG_PLL_12                    ; /* 0xb0 */
    volatile unsigned int           reserved_7[19]                   ; /* 0xb4~0xfc */
    volatile U_SC_POWER_STAT        SC_POWER_STAT                    ; /* 0x100 */
    volatile unsigned int           SC_LP_START                      ; /* 0x104 */
    volatile U_SC_LOW_POWER_STAT    SC_LOW_POWER_STAT                ; /* 0x108 */
    volatile unsigned int           reserved_8[13]                   ; /* 0x10c~0x13c */
    volatile unsigned int           SC_BUS_CORE_PD_COUNT             ; /* 0x140 */
    volatile unsigned int           SC_CORE_PD_RST_COUNT             ; /* 0x144 */
    volatile unsigned int           SC_CORE_PWRUP_COUNT              ; /* 0x148 */
    volatile unsigned int           SC_CORE_PWRUP_RST_COUNT          ; /* 0x14c */
    volatile unsigned int           SC_DDR_SREF_PD_COUNT             ; /* 0x150 */
    volatile unsigned int           SC_DDRPHY_IO_OE_COUNT            ; /* 0x154 */
    volatile unsigned int           SC_ISO_PD_COUNT                  ; /* 0x158 */
    volatile unsigned int           SC_ISO_PU_COUNT                  ; /* 0x15c */
    volatile unsigned int           reserved_9[8]                    ; /* 0x160~0x17c */
    volatile U_SC_DDRPHY_LP_EN      SC_DDRPHY_LP_EN                  ; /* 0x180 */
    volatile unsigned int           reserved_10[3]                   ; /* 0x184~0x18c */
    volatile U_SC_AIDSP_PWRUP_CTRL   SC_AIDSP_PWRUP_CTRL              ; /* 0x190 */
    volatile U_SC_AIDSP_PWRUP_STAT   SC_AIDSP_PWRUP_STAT              ; /* 0x194 */
    volatile unsigned int           reserved_11[2]                   ; /* 0x198~0x19c */
    volatile U_SC_HPM0_CTRL0        SC_HPM0_CTRL0                    ; /* 0x1a0 */
    volatile U_SC_HPM0_CTRL1        SC_HPM0_CTRL1                    ; /* 0x1a4 */
    volatile U_SC_HPM0_CTRL2        SC_HPM0_CTRL2                    ; /* 0x1a8 */
    volatile U_SC_HPM0_CTRL3        SC_HPM0_CTRL3                    ; /* 0x1ac */
    volatile U_SC_HPM0_CTRL4        SC_HPM0_CTRL4                    ; /* 0x1b0 */
    volatile unsigned int           reserved_12[7]                   ; /* 0x1b4~0x1cc */
    volatile U_SC_SHPM0_CTRL0       SC_SHPM0_CTRL0                   ; /* 0x1d0 */
    volatile U_SC_SHPM0_CTRL1       SC_SHPM0_CTRL1                   ; /* 0x1d4 */
    volatile unsigned int           reserved_13[2]                   ; /* 0x1d8~0x1dc */
    volatile U_SC_PWM_CTRL0         SC_PWM_CTRL0                     ; /* 0x1e0 */
    volatile U_SC_PWM_CTRL1         SC_PWM_CTRL1                     ; /* 0x1e4 */
    volatile U_SC_PWM_CTRL2         SC_PWM_CTRL2                     ; /* 0x1e8 */
    volatile unsigned int           reserved_14[5]                   ; /* 0x1ec~0x1fc */
    volatile U_SC_CACHE_SIZE_CFG    SC_CACHE_SIZE_CFG                ; /* 0x200 */
    volatile unsigned int           reserved_15[15]                  ; /* 0x204~0x23c */
    volatile U_SC_DOLBY_CTRL        SC_DOLBY_CTRL                    ; /* 0x240 */
    volatile unsigned int           reserved_16[15]                  ; /* 0x244~0x27c */
    volatile unsigned int           SC_CHECKSUM_MASK                 ; /* 0x280 */
    volatile unsigned int           reserved_17[47]                  ; /* 0x284~0x33c */
    volatile unsigned int           SC_HDMIRX_AON_CFG                ; /* 0x340 */
    volatile unsigned int           reserved_18[47]                  ; /* 0x344~0x3fc */
    volatile unsigned int           SC_HDMITX_CPU_CEC_INFO_0         ; /* 0x400 */
    volatile unsigned int           SC_HDMITX_CPU_CEC_INFO_1         ; /* 0x404 */
    volatile unsigned int           SC_HDMITX_CPU_MCU_SWITCH_INFO    ; /* 0x408 */
    volatile unsigned int           SC_HDMITX_CPU_RESERVED_0         ; /* 0x40c */
    volatile unsigned int           SC_HDMITX_CPU_RESERVED_1         ; /* 0x410 */
    volatile unsigned int           SC_HDMITX_CPU_RESERVED_2         ; /* 0x414 */
    volatile unsigned int           SC_HDMITX_CPU_RESERVED_3         ; /* 0x418 */
    volatile unsigned int           SC_HDMITX_CPU_RESERVED_4         ; /* 0x41c */
    volatile unsigned int           reserved_19[8]                   ; /* 0x420~0x43c */
    volatile unsigned int           SC_HDMITX_MCU_CEC_INFO_0         ; /* 0x440 */
    volatile unsigned int           SC_HDMITX_MCU_CEC_INFO_1         ; /* 0x444 */
    volatile unsigned int           SC_HDMITX_MCU_CPU_SWITCH_INFO    ; /* 0x448 */
    volatile unsigned int           SC_HDMITX_MCU_RESERVED_0         ; /* 0x44c */
    volatile unsigned int           SC_HDMITX_MCU_RESERVED_1         ; /* 0x450 */
    volatile unsigned int           SC_HDMITX_MCU_RESERVED_2         ; /* 0x454 */
    volatile unsigned int           SC_HDMITX_MCU_RESERVED_3         ; /* 0x458 */
    volatile unsigned int           SC_HDMITX_MCU_RESERVED_4         ; /* 0x45c */
    volatile unsigned int           reserved_20[48]                  ; /* 0x460~0x51c */
    volatile U_SC_MCU_LDO_CTRL      SC_MCU_LDO_CTRL                  ; /* 0x520 */
    volatile U_SC_MCU_LDO_STAT      SC_MCU_LDO_STAT                  ; /* 0x524 */
    volatile unsigned int           reserved_21[6]                   ; /* 0x528~0x53c */
    volatile U_SC_LSADC_CTRL        SC_LSADC_CTRL                    ; /* 0x540 */
    volatile U_SC_LSADC_DATA        SC_LSADC_DATA                    ; /* 0x544 */
    volatile U_SC_LSADC_DATA1       SC_LSADC_DATA1                   ; /* 0x548 */
    volatile unsigned int           reserved_22[45]                  ; /* 0x54c~0x5fc */
    volatile unsigned int           SC_DDRCA_REE_CNT                 ; /* 0x600 */
    volatile unsigned int           SC_DDRCA_KEY_PRESERVATION        ; /* 0x604 */
    volatile unsigned int           reserved_23[54]                  ; /* 0x608~0x6dc */
    volatile unsigned int           SC_DDRCA_RNG_TEE0                ; /* 0x6e0 */
    volatile unsigned int           SC_DDRCA_RNG_TEE1                ; /* 0x6e4 */
    volatile unsigned int           SC_DDRCA_RNG_REE0                ; /* 0x6e8 */
    volatile unsigned int           SC_DDRCA_RNG_REE1                ; /* 0x6ec */
    volatile unsigned int           reserved_24[4]                   ; /* 0x6f0~0x6fc */
    volatile unsigned int           SC_MEM_REPAIR_CTRL0              ; /* 0x700 */
    volatile unsigned int           SC_MEM_REPAIR_CTRL1              ; /* 0x704 */
    volatile U_SC_MEM_REPAIR_CTRL2   SC_MEM_REPAIR_CTRL2              ; /* 0x708 */
    volatile unsigned int           reserved_25[13]                  ; /* 0x70c~0x73c */
    volatile U_SC_MEM_REPAIR_STAT   SC_MEM_REPAIR_STAT               ; /* 0x740 */
    volatile unsigned int           reserved_26[47]                  ; /* 0x744~0x7fc */
    volatile U_SC_FSENSOR_CTRL0     SC_FSENSOR_CTRL0                 ; /* 0x800 */
    volatile U_SC_FSENSOR_CTRL1     SC_FSENSOR_CTRL1                 ; /* 0x804 */
    volatile unsigned int           reserved_27[2]                   ; /* 0x808~0x80c */
    volatile U_SC_FSENSOR_STATE0    SC_FSENSOR_STATE0                ; /* 0x810 */
    volatile U_SC_FSENSOR_STATE1    SC_FSENSOR_STATE1                ; /* 0x814 */
    volatile unsigned int           SC_FSENSOR_STATE2                ; /* 0x818 */
    volatile unsigned int           SC_FSENSOR_STATE3                ; /* 0x81c */
    volatile unsigned int           reserved_28[56]                  ; /* 0x820~0x8fc */
    volatile U_SC_INTF_IO_SEL       SC_INTF_IO_SEL                   ; /* 0x900 */
    volatile U_SC_GPIO_IO_SEL       SC_GPIO_IO_SEL                   ; /* 0x904 */
    volatile unsigned int           reserved_29[126]                 ; /* 0x908~0xafc */
    volatile U_SC_SOFT_INT          SC_SOFT_INT                      ; /* 0xb00 */
    volatile unsigned int           reserved_30[3]                   ; /* 0xb04~0xb0c */
    volatile U_SC_SOFT_INT_MASK     SC_SOFT_INT_MASK                 ; /* 0xb10 */
    volatile unsigned int           reserved_31[3]                   ; /* 0xb14~0xb1c */
    volatile U_SC_INT_STATE         SC_INT_STATE                     ; /* 0xb20 */
    volatile unsigned int           reserved_32[23]                  ; /* 0xb24~0xb7c */
    volatile U_SC_AIDSP_INT_MASK    SC_AIDSP_INT_MASK                ; /* 0xb80 */
    volatile U_SC_AIDSP_INT_CLR     SC_AIDSP_INT_CLR                 ; /* 0xb84 */
    volatile U_SC_AIDSP_INT_STATE   SC_AIDSP_INT_STATE               ; /* 0xb88 */
    volatile U_SC_AIDSP_INT_MASK_STATE   SC_AIDSP_INT_MASK_STATE          ; /* 0xb8c */
    volatile unsigned int           reserved_33[12]                  ; /* 0xb90~0xbbc */
    volatile U_SC_INT_COUNT_STATE   SC_INT_COUNT_STATE               ; /* 0xbc0 */
    volatile unsigned int           reserved_34[15]                  ; /* 0xbc4~0xbfc */
    volatile unsigned int           SC_DOLBY_GENn[12]                ; /* 0xc00~0xc2c */
    volatile unsigned int           reserved_35[244]                 ; /* 0xc30~0xffc */
    volatile unsigned int           SC_HPP_GENx[16]                  ; /* 0x1000~0x103c */
    volatile unsigned int           reserved_36[240]                 ; /* 0x1040~0x13fc */
    volatile unsigned int           SC_GENm[24]                      ; /* 0x1400~0x145c */
    volatile unsigned int           reserved_37[232]                 ; /* 0x1460~0x17fc */
    volatile unsigned int           SC_GENx[40]                      ; /* 0x1800~0x189c */

} S_SYSCTRL_REGS_TYPE;

#endif /* __HI_REG_SYS_H__ */
