/*
 * Copyright (C) Hisilicon Technologies Co., Ltd. 2019. All rights reserved.
 * Description: lpmuc ram config
 */

#ifndef __LPMCU_RAM_CONFIG_H__
#define __LPMCU_RAM_CONFIG_H__

/*
 * 0 ~ 0xe000       lpmuc_code
 * 0xe000 ~ 0xee00  suspend_param
 * 0xee00 ~ 0xef00  wakeup_param
 * 0xf000 ~ 0xffff  xdata
 */

#define LPMCU_RAM_BASE 0x800000
#define LPMCU_SIZE 0x10000 /* 64k */
#define LPMCU_CODE_MAXSIZE 0xe000

#define LPMCU_STANDBY_DATA_ADDR 0xe000
#define LPMCU_STANDBY_DATA_SIZE 0xe00

#define LPMCU_WAKEUP_DATA_ADDR (LPMCU_STANDBY_DATA_ADDR + LPMCU_STANDBY_DATA_SIZE)
#define LPMCU_WAKEUP_DATA_SIZE 0x20

#define LPMCU_CHIP_TYPE_ADDR (LPMCU_STANDBY_DATA_ADDR + 0x0)
#define LPMCU_CHIP_VERSION_ADDR (LPMCU_CHIP_TYPE_ADDR + 0x4)

#define LPMCU_KEYLED_SUSPEND_PARAM_ADDR (LPMCU_STANDBY_DATA_ADDR + 0x8)
#define LPMCU_KEYLED_TYPE_ADDR (LPMCU_KEYLED_SUSPEND_PARAM_ADDR + 0x4)
#define LPMCU_KEYLED_WAKEUP_KEY_ADDR (LPMCU_KEYLED_TYPE_ADDR + 0x4)
#define LPMCU_KEYLED_DISPLAY_ADDR (LPMCU_STANDBY_DATA_ADDR + 0x14)
#define LPMCU_KEYLED_DISPLAY_VALUE_ADDR (LPMCU_KEYLED_DISPLAY_ADDR + 0x4)

#define LPMCU_GPIO_SUSPEND_PARAM_ADDR (LPMCU_STANDBY_DATA_ADDR + 0x1C)
#define LPMCU_GPIO_SUSPEND_PARAM0_ADDR (LPMCU_GPIO_SUSPEND_PARAM_ADDR + 0x4)
#define LPMCU_GPIO_POWEROFF_PARAM_ADDR (LPMCU_STANDBY_DATA_ADDR + 0x40)
#define LPMCU_GPIO_POWEROFF_PARAM0_ADDR (LPMCU_STANDBY_DATA_ADDR + 0x40)

#define LPMCU_ETH_SUSPEND_PARAM_ADDR (LPMCU_STANDBY_DATA_ADDR + 0x64)
#define LPMCU_ETH_TO_PASSIVE_STANDBY_ADDR (LPMCU_ETH_SUSPEND_PARAM_ADDR + 0x4)

#define LPMCU_TIMEOUT_SUSPEND_PARAM_ADDR (LPMCU_STANDBY_DATA_ADDR + 0x6C)
#define LPMCU_TIMEOUT_SUSPEND_TIME_ADDR (LPMCU_TIMEOUT_SUSPEND_PARAM_ADDR + 0x4)
#define LPMCU_DBG_MASK_ADDR (LPMCU_STANDBY_DATA_ADDR + 0x74)
#define LPMCU_RESUME_RESET_ADDR (LPMCU_STANDBY_DATA_ADDR + 0x74)

#define LPMCU_HDMI_SUSPEND_PARAM_ADDR (LPMCU_STANDBY_DATA_ADDR + 0x78)
#define LPMCU_HDMIRX_PLUGIN_PORT_ADDR (LPMCU_HDMI_SUSPEND_PARAM_ADDR + 0x4)
#define LPMCU_HDMITX_CEC_PARAM_ADDR (LPMCU_HDMI_SUSPEND_PARAM_ADDR + 0x8)

#define LPMCU_IR_SUSPEND_PARAM_ADDR (LPMCU_STANDBY_DATA_ADDR + 0x98)
#define LPMCU_IR_LOW_VALUE_ADDR (LPMCU_IR_SUSPEND_PARAM_ADDR + 0x4)
#define LPMCU_IR_HIGH_VALUE_ADDR (LPMCU_IR_SUSPEND_PARAM_ADDR + 0x8)

#define LPMCU_USB_SUSPEND_PARAM_ADDR (LPMCU_STANDBY_DATA_ADDR + 0x12C)
#define LPMCU_UART_SUSPEND_PARAM_ADDR (LPMCU_STANDBY_DATA_ADDR + 0x130)

#define LPMCU_START_IN_BOOT_ADDR    (LPMCU_STANDBY_DATA_ADDR + 0x134)
#define LPMCU_ENTER_SUSPEND_IN_BOOT_ADDR  (LPMCU_STANDBY_DATA_ADDR + 0x138)

#define LPMCU_WAKEUP_TYPE (LPMCU_WAKEUP_DATA_ADDR + 0x0)
#define LPMCU_WAKEUP_GPIO (LPMCU_WAKEUP_DATA_ADDR + 0x04)
#define LPMCU_WAKEUP_IR_KEYLOW (LPMCU_WAKEUP_DATA_ADDR + 0x8)
#define LPMCU_WAKEUP_IR_KEYHIGH (LPMCU_WAKEUP_DATA_ADDR + 0xC)
#define LPMCU_STANDBY_PERIOD (LPMCU_WAKEUP_DATA_ADDR + 0x10)

#define LPMCU_START_IN_BOOT_FLAG    0x5A5AA5A5
#define ENTER_SUSPEND_IN_BOOT_FLAG  0x5A5AA5A5
#define TEMP_CHECK_TO_SUSPEND 0x11111111

#define LPMCU_WAKEUP_GPIO_MAXNUM 4
#define LPMCU_WAKEUP_IRKEY_MAXNUM 10
#define LPMCU_POWEROFF_GPIO_MAXNUM 4
#define LPMCU_WAKEUP_HDMITX_ID_MAXNUM 4

#endif
